-- Flow / Spirit — 17 Yoga & Mobility asanas + legacy session updates
-- Run after 010_library_flow_spirit_healer.sql

insert into public.library_flow_spirit (
  slug,
  pillar,
  session_name,
  description,
  duration_minutes,
  tempo_profile,
  complexity_level,
  target_recovery_zones,
  complexity_tier,
  is_dynamic_flow,
  default_hold_seconds
) values
  (
    'childs_pose',
    'flow',
    'Child''s Pose (Balasana)',
    'Kneeling rest — decompresses lumbar spine after axial Iron loading.',
    4,
    '{"type":"static_hold","breath":"belly"}'::jsonb,
    1,
    array['lower_back', 'hips'],
    1,
    false,
    60
  ),
  (
    'cat_cow_flow',
    'flow',
    'Cat–Cow Flow',
    'Segmental spinal flexion/extension — synovial warm-up for lower back and thoracic spine.',
    5,
    '{"type":"dynamic_reps","reps":10,"breath_linked":true}'::jsonb,
    1,
    array['lower_back', 'thoracic_spine'],
    1,
    true,
    0
  ),
  (
    'downward_dog',
    'flow',
    'Downward-Facing Dog',
    'Posterior chain lengthening — hamstrings, calves, shoulders after push/pull Iron.',
    5,
    '{"type":"static_hold","breath":"nasal"}'::jsonb,
    2,
    array['hamstrings', 'shoulders', 'lower_back'],
    1,
    false,
    45
  ),
  (
    'pigeon_pose',
    'flow',
    'Pigeon Pose (Eka Pada Rajakapotasana)',
    'Deep hip external rotation — glute and hip recovery post squats, hinges, and kick volume.',
    6,
    '{"type":"static_hold","sides":"each"}'::jsonb,
    3,
    array['hips', 'glutes'],
    2,
    false,
    90
  ),
  (
    'supine_twist',
    'flow',
    'Supine Spinal Twist',
    'Decompresses lumbar facet joints — pairs with heavy deadlift and combat rotation fatigue.',
    5,
    '{"type":"static_hold","sides":"each"}'::jsonb,
    2,
    array['lower_back', 'thoracic_spine'],
    1,
    false,
    60
  ),
  (
    'happy_baby',
    'flow',
    'Happy Baby (Ananda Balasana)',
    'Hip flexor and sacral release — counterbalance hip hinge and low kick loading.',
    4,
    '{"type":"static_hold","breath":"slow_exhale"}'::jsonb,
    2,
    array['hips', 'lower_back', 'glutes'],
    1,
    false,
    60
  ),
  (
    'seated_forward_fold',
    'flow',
    'Seated Forward Fold (Paschimottanasana)',
    'Hamstring and erector lengthening — essential after RDL, leg curl, and hinge days.',
    5,
    '{"type":"static_hold","knee":"soft"}'::jsonb,
    2,
    array['hamstrings', 'lower_back'],
    1,
    false,
    75
  ),
  (
    'couch_stretch',
    'flow',
    'Couch Stretch (Half-Kneeling Quad)',
    'Rectus femoris and hip flexor release — post squat and lunge dominant Iron sessions.',
    6,
    '{"type":"static_hold","sides":"each"}'::jsonb,
    3,
    array['hips', 'hamstrings'],
    2,
    false,
    90
  ),
  (
    'frog_stretch',
    'flow',
    'Frog Stretch',
    'Adductor and deep hip capsule opener — complements combat hip rotation volume.',
    5,
    '{"type":"static_hold","breath":"box"}'::jsonb,
    3,
    array['hips', 'glutes'],
    2,
    false,
    75
  ),
  (
    'worlds_greatest_stretch',
    'flow',
    'World''s Greatest Stretch',
    'Dynamic hip flexor, hamstring, and thoracic opener — full-chain reset between pillars.',
    8,
    '{"type":"dynamic_reps","reps":6,"sides":"each"}'::jsonb,
    4,
    array['hips', 'hamstrings', 'thoracic_spine'],
    2,
    true,
    0
  ),
  (
    'thread_the_needle',
    'flow',
    'Thread the Needle',
    'Thoracic rotation with shoulder stability — desk and bench press recovery.',
    4,
    '{"type":"static_hold","sides":"each"}'::jsonb,
    2,
    array['thoracic_spine', 'shoulders'],
    1,
    false,
    45
  ),
  (
    'wall_angels',
    'flow',
    'Wall Angels',
    'Scapular upward rotation — shoulder longevity after pressing and clinch work.',
    5,
    '{"type":"dynamic_reps","reps":12}'::jsonb,
    2,
    array['shoulders', 'thoracic_spine'],
    1,
    true,
    0
  ),
  (
    'shoulder_dislocates_band',
    'flow',
    'Shoulder Dislocates (Band)',
    'Glenohumeral capsule mobility — prehab for combat overhead volume.',
    4,
    '{"type":"dynamic_reps","reps":15,"equipment":"band"}'::jsonb,
    2,
    array['shoulders'],
    1,
    true,
    0
  ),
  (
    'revolved_low_lunge',
    'flow',
    'Revolved Low Lunge',
    'Hip flexor plus thoracic twist — links lower-body Iron fatigue to rotational balance.',
    6,
    '{"type":"static_hold","sides":"each"}'::jsonb,
    3,
    array['hips', 'thoracic_spine', 'lower_back'],
    2,
    false,
    60
  ),
  (
    'ankle_mobility_flow',
    'flow',
    'Ankle Mobility Flow',
    'Knee-over-toe rocks and calf releases — combat footwork and squat ankle demand.',
    5,
    '{"type":"dynamic_reps","reps":10,"sides":"each"}'::jsonb,
    2,
    array['ankles', 'hamstrings'],
    1,
    true,
    0
  ),
  (
    'neck_release_flow',
    'flow',
    'Neck Release Flow',
    'Gentle cervical CARs — high-stress and combat head-movement recovery.',
    4,
    '{"type":"dynamic_reps","reps":8,"direction":"slow"}'::jsonb,
    1,
    array['neck', 'shoulders'],
    1,
    true,
    0
  ),
  (
    'standing_hamstring_floss',
    'flow',
    'Standing Hamstring Floss',
    'Neural gliding for posterior chain — post heavy hinge and kick sessions.',
    4,
    '{"type":"dynamic_reps","reps":12,"sides":"each"}'::jsonb,
    2,
    array['hamstrings', 'lower_back'],
    2,
    true,
    0
  ),
  (
    'morning_joint_flow',
    'flow',
    'Morning Joint Flow',
    'Slow articular rotations and sun-salutation style transitions for synovial fluid and posture.',
    18,
    '{"focus":"mobility","segments":["neck","shoulders","hips","ankles"],"intensity":"low"}'::jsonb,
    2,
    array['neck', 'shoulders', 'hips', 'ankles'],
    1,
    true,
    30
  ),
  (
    'hip_opener_sequence',
    'flow',
    'Hip Opener Sequence',
    'Pigeon variations, 90/90 switches, and controlled Cossack patterns for hip longevity.',
    22,
    '{"focus":"hips","hold_seconds":45,"transitions":"breath-linked"}'::jsonb,
    4,
    array['hips', 'glutes', 'lower_back'],
    2,
    true,
    45
  ),
  (
    'tempo_box_breathwork',
    'spirit',
    'Box Breathing',
    'Equal inhale, hold, exhale, hold — nervous system regulation before Iron or Combat.',
    12,
    '{"inhale_seconds":4,"hold_seconds":4,"exhale_seconds":4,"hold_empty_seconds":4,"cycles":8}'::jsonb,
    2,
    array['neck', 'thoracic_spine'],
    1,
    false,
    0
  ),
  (
    'recovery_478',
    'spirit',
    '4-7-8 Recovery Breath',
    'Downregulation protocol for high-stress days or post-max-effort sessions.',
    15,
    '{"inhale_seconds":4,"hold_seconds":7,"exhale_seconds":8,"hold_empty_seconds":0,"cycles":6}'::jsonb,
    3,
    array['lower_back'],
    1,
    false,
    0
  ),
  (
    'nsdr_body_scan',
    'spirit',
    'NSDR Body Scan',
    'Non-sleep deep rest progressive relaxation for recovery and vagal tone.',
    20,
    '{"inhale_seconds":4,"exhale_seconds":6,"body_scan":true,"cycles":10}'::jsonb,
    4,
    array['lower_back', 'hips', 'shoulders'],
    2,
    false,
    0
  ),
  (
    'relaxing_exhale',
    'spirit',
    'Relaxing Exhale',
    'Gentle 4-0-6 downregulation primer for low-fatigue days before Iron or Combat.',
    12,
    '{"inhale_seconds":4,"hold_seconds":0,"exhale_seconds":6,"hold_empty_seconds":0,"cycles":5}'::jsonb,
    2,
    array['neck', 'thoracic_spine'],
    1,
    false,
    0
  )
on conflict (slug) do update set
  pillar = excluded.pillar,
  session_name = excluded.session_name,
  description = excluded.description,
  duration_minutes = excluded.duration_minutes,
  tempo_profile = excluded.tempo_profile,
  complexity_level = excluded.complexity_level,
  target_recovery_zones = excluded.target_recovery_zones,
  complexity_tier = excluded.complexity_tier,
  is_dynamic_flow = excluded.is_dynamic_flow,
  default_hold_seconds = excluded.default_hold_seconds;
