/**
 * Elite Hypertrophy offline catalog — generated from supabase/seed_hypertrophy.sql
 * Do not edit by hand. Regenerate with: npx tsx scripts/extractEliteCatalog.ts
 *
 * Anatomical sub-group mapping lives in `lib/catalog/eliteAnatomicalMap.ts`
 * and is applied by `buildExerciseCatalog` (survives seed regeneration).
 */
import type { LibraryExercise } from '@/types/catalog';

export const ELITE_EXERCISES: readonly LibraryExercise[] = [
  {
    id: "96106773-3f44-5833-933e-1200434d9ad9",
    slug: "deficit_bulgarian_split_squat",
    name: "Deficit Bulgarian Split Squat",
    biomechanical_instructions: {"setup":"Front foot on 2–4\" deficit, rear foot elevated, torso slight forward for quad bias.","eccentric":"3s lower until rear knee nears floor; front knee tracks over mid-foot.","concentric":"Drive through front heel; minimize push from back leg.","safety":"Reduce deficit if knee shear pain; hold dumbbells at sides for balance."},
    equipment_required: ["dumbbells","full_gym","bodyweight"],
    default_sets: 3,
    default_reps: 10,
    movement_pattern: "lunge",
    primary_muscle: "quadriceps",
    synergist_muscles: ["glutes","adductors","core"],
    cns_fatigue_cost: 4,
    joint_stress_profile: "high_knee_shear",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "189293a4-100d-5363-9efc-1c7d5ea115e1",
    slug: "hack_squat_machine",
    name: "Hack Squat (Machine)",
    biomechanical_instructions: {"setup":"Feet mid-platform, back flat on pad, knees align with toes.","eccentric":"Controlled 2–3s to deep knee flexion without pelvis tuck.","concentric":"Press through mid-foot; avoid locking knees violently.","safety":"Limit depth if lumbar rounds off pad."},
    equipment_required: ["full_gym"],
    default_sets: 4,
    default_reps: 8,
    movement_pattern: "squat",
    primary_muscle: "quadriceps",
    synergist_muscles: ["glutes"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "moderate_knee_stress",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "9c6ccfa8-f566-5f47-adeb-11245deb488a",
    slug: "pendulum_squat",
    name: "Pendulum Squat",
    biomechanical_instructions: {"setup":"Shoulders under pads, feet low on platform for quad emphasis.","eccentric":"Let arc guide depth; keep ribs stacked.","concentric":"Drive knees forward over toes; constant tension arc.","safety":"Stop above pain-limited ROM."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 10,
    movement_pattern: "squat",
    primary_muscle: "quadriceps",
    synergist_muscles: ["glutes"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "moderate_knee_stress",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "6ce0cfb7-f62a-51e0-8c74-76954e8f381e",
    slug: "belt_squat",
    name: "Belt Squat",
    biomechanical_instructions: {"setup":"Belt at hips, hold straps, upright torso, feet shoulder-width.","eccentric":"Sit between hips without spinal compression.","concentric":"Drive floor; glutes and quads without axial load.","safety":"Ideal when low-back fatigue is high."},
    equipment_required: ["full_gym"],
    default_sets: 4,
    default_reps: 10,
    movement_pattern: "squat",
    primary_muscle: "quadriceps",
    synergist_muscles: ["glutes","adductors"],
    cns_fatigue_cost: 2,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "3d07d12a-4c5e-5c3c-97e9-f39d16518cc7",
    slug: "barbell_back_squat",
    name: "Barbell Back Squat",
    biomechanical_instructions: {"setup":"High-bar or low-bar, brace 360°, heels hip-width.","eccentric":"Sit between hips; knees track toes; neutral spine.","concentric":"Drive floor; hips and chest rise together.","safety":"Safety bars set; avoid valgus collapse."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 4,
    default_reps: 6,
    movement_pattern: "squat",
    primary_muscle: "quadriceps",
    synergist_muscles: ["glutes","erectors","core"],
    cns_fatigue_cost: 5,
    joint_stress_profile: "spinal_axial_load",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "5a3c8528-b79c-5333-b4ca-7c3e9886ad3c",
    slug: "sissy_squat",
    name: "Sissy Squat",
    biomechanical_instructions: {"setup":"Heels elevated or anchored, hips extended, torso lean.","eccentric":"3s knee flexion with hips open — pure quad lengthening.","concentric":"Extend knees without hip closure.","safety":"Use band assist if patellar irritation."},
    equipment_required: ["bodyweight","full_gym"],
    default_sets: 3,
    default_reps: 12,
    // Isolation finisher — not a session opener / primary compound.
    movement_pattern: "isolation",
    primary_muscle: "quadriceps",
    synergist_muscles: ["core"],
    cns_fatigue_cost: 2,
    joint_stress_profile: "high_knee_shear",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "cc385cc5-8018-519c-a3b7-238217c344b2",
    slug: "leg_extension",
    name: "Leg Extension",
    biomechanical_instructions: {"setup":"Pad at ankle, femur neutral, back flat on seat.","eccentric":"3s lower without hip lift off seat.","concentric":"Extend to peak contraction; pause 1s.","safety":"Avoid if active patellar tendinopathy."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 15,
    movement_pattern: "isolation",
    primary_muscle: "quadriceps",
    synergist_muscles: [],
    cns_fatigue_cost: 1,
    joint_stress_profile: "moderate_knee_stress",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "519fbd94-c123-5c45-ba62-b64e6d1b2f92",
    slug: "seated_leg_curl",
    name: "Seated Leg Curl",
    biomechanical_instructions: {"setup":"Pad above heels, hips pinned, dorsiflex ankles optional.","eccentric":"3s lower to full hamstring stretch.","concentric":"Curl without lifting hips.","safety":"Control tempo — avoid ballistic reps."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "hamstrings",
    synergist_muscles: ["calves"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "afaab38f-24f5-54d4-aba5-bba50dcbb53b",
    slug: "nordic_curl",
    name: "Nordic Hamstring Curl",
    biomechanical_instructions: {"setup":"Ankles fixed, tall line knee to shoulder.","eccentric":"Lower as slow as possible using hamstrings as brakes.","concentric":"Push lightly from floor if needed.","regression":"Band assist at chest."},
    equipment_required: ["bodyweight","full_gym"],
    default_sets: 3,
    default_reps: 6,
    movement_pattern: "isolation",
    primary_muscle: "hamstrings",
    synergist_muscles: ["glutes","calves"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "high_knee_shear",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "091dd280-040c-5b35-8191-8abb917b2642",
    slug: "barbell_romanian_deadlift",
    name: "Barbell Romanian Deadlift",
    biomechanical_instructions: {"setup":"Soft knee bend, bar close to legs, lats engaged, ribs down.","eccentric":"Hinge until hamstrings peak stretch; shins near vertical.","concentric":"Glute drive; bar skims thighs.","safety":"Stop if lumbar flexion appears."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 4,
    default_reps: 8,
    movement_pattern: "hinge",
    primary_muscle: "hamstrings",
    synergist_muscles: ["glutes","erectors"],
    cns_fatigue_cost: 4,
    joint_stress_profile: "lumbar_shear",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "af7c3b17-9e4a-5036-ae5f-9bc858610742",
    slug: "dumbbell_romanian_deadlift",
    name: "Dumbbell Romanian Deadlift",
    biomechanical_instructions: {"setup":"Soft knee bend, bells close to thighs, neutral spine.","eccentric":"Hinge to hamstring end-range; feel stretch at bottom.","concentric":"Squeeze glutes; avoid hyperextension.","safety":"Reduce load if grip limits set before hamstrings."},
    equipment_required: ["dumbbells","full_gym"],
    default_sets: 4,
    default_reps: 10,
    movement_pattern: "hinge",
    primary_muscle: "hamstrings",
    synergist_muscles: ["glutes","erectors"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "lumbar_shear",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "58396536-6623-576d-9ac5-d8547be9c47b",
    slug: "stiff_leg_deadlift",
    name: "Stiff-Leg Deadlift",
    biomechanical_instructions: {"setup":"Minimal knee bend, bar over mid-foot, hinge from hips.","eccentric":"Bar tracks close; maximize hamstring length.","concentric":"Hip extension without back hyperextension.","safety":"Lighter than RDL if lumbar fatigue high."},
    equipment_required: ["barbell","dumbbells","full_gym"],
    default_sets: 3,
    default_reps: 10,
    movement_pattern: "hinge",
    primary_muscle: "hamstrings",
    synergist_muscles: ["glutes","erectors"],
    cns_fatigue_cost: 4,
    joint_stress_profile: "lumbar_shear",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "b67c0ffe-1533-5e23-a8b4-b13612893c95",
    slug: "conventional_deadlift",
    name: "Conventional Deadlift",
    biomechanical_instructions: {"setup":"Mid-foot bar, hinge, lats on, neutral neck.","eccentric":"Controlled lower or reset per block.","concentric":"Floor push, hips through, glutes lock.","safety":"No rounding; treat as high CNS day."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 4,
    default_reps: 5,
    movement_pattern: "hinge",
    primary_muscle: "erectors",
    synergist_muscles: ["glutes","hamstrings","quadriceps","traps"],
    cns_fatigue_cost: 5,
    joint_stress_profile: "spinal_axial_load",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "103c9b5d-a16c-5266-868b-27568d67b324",
    slug: "rack_pull",
    name: "Rack Pull (Below Knee)",
    biomechanical_instructions: {"setup":"Bar at just below knee, wedge, lats tight.","eccentric":"Lower to pins with control.","concentric":"Lock hips; overload posterior chain.","safety":"Use when deadlift fatigue is managed separately."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 4,
    default_reps: 5,
    movement_pattern: "hinge",
    primary_muscle: "erectors",
    synergist_muscles: ["glutes","traps","hamstrings"],
    cns_fatigue_cost: 4,
    joint_stress_profile: "spinal_axial_load",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "7f5ebb84-5d18-5103-a8ef-b5a67ab28939",
    slug: "barbell_hip_hinge_good_morning",
    name: "Barbell Good Morning",
    biomechanical_instructions: {"setup":"Bar on back like squat, soft knees, brace hard.","eccentric":"Hinge until hamstrings limit ROM.","concentric":"Glute-ham drive to stand.","safety":"Light load; advanced athletes only."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 3,
    default_reps: 8,
    movement_pattern: "hinge",
    primary_muscle: "hamstrings",
    synergist_muscles: ["glutes","erectors"],
    cns_fatigue_cost: 4,
    joint_stress_profile: "lumbar_shear",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "67fa063d-7501-59a0-b183-d84b3cfc2f55",
    slug: "hip_thrust_barbell",
    name: "Barbell Hip Thrust",
    biomechanical_instructions: {"setup":"Upper back on bench, bar padded, chin tucked, ribs down.","eccentric":"Lower until stretch at bottom without lumbar arch.","concentric":"Full glute lockout; shins vertical at top.","safety":"Pause at top; avoid cervical hyperextension."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 4,
    default_reps: 10,
    movement_pattern: "hinge",
    primary_muscle: "glutes",
    synergist_muscles: ["hamstrings","core"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "0632c3c8-dd10-58b9-8be3-383ce4630587",
    slug: "cable_kickback_glute",
    name: "Cable Glute Kickback",
    biomechanical_instructions: {"setup":"Ankle strap, slight forward lean, squeeze at top.","eccentric":"3s return without spinal rotation.","concentric":"Extend hip behind body; glute-only path.","safety":"Avoid excessive lumbar extension."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 15,
    movement_pattern: "isolation",
    primary_muscle: "glutes",
    synergist_muscles: ["hamstrings"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "c14832cc-fad4-53a7-aedd-b49f5ef09260",
    slug: "incline_dumbbell_press_30",
    name: "Incline Dumbbell Press (30°)",
    biomechanical_instructions: {"setup":"Bench 30° — clavicular head bias; feet planted, scapulae retracted.","eccentric":"3s to upper chest line; elbows 45°.","concentric":"Press up and slightly in; dumbbells independent path.","safety":"30° reduces impingement vs steep incline."},
    equipment_required: ["dumbbells","full_gym"],
    default_sets: 4,
    default_reps: 10,
    movement_pattern: "push",
    primary_muscle: "upper_chest",
    synergist_muscles: ["front_delts","triceps"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "shoulder_impingement_risk",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "2f9eeb1d-8f3d-55d0-a0db-6cc265810af7",
    slug: "incline_cable_fly",
    name: "Incline Cable Fly (30°)",
    biomechanical_instructions: {"setup":"Bench 30°, cables low, slight elbow bend fixed.","eccentric":"Arc down until upper chest stretch.","concentric":"Sweep up on fiber line; constant tension.","safety":"Light-moderate load; stretch is the stimulus."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "upper_chest",
    synergist_muscles: ["front_delts"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "shoulder_impingement_risk",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "20a5a9f6-a1e1-5cff-9f6a-93de97bbcf75",
    slug: "barbell_bench_press",
    name: "Barbell Bench Press",
    biomechanical_instructions: {"setup":"Feet flat, arch legal, wrists over elbows, scapulae pinned.","eccentric":"3s to mid-chest.","concentric":"Leg drive, press to lockout.","safety":"Spotter or safeties."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 4,
    default_reps: 8,
    movement_pattern: "push",
    primary_muscle: "chest",
    synergist_muscles: ["front_delts","triceps"],
    cns_fatigue_cost: 4,
    joint_stress_profile: "shoulder_impingement_risk",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "1660c64e-f50f-55f7-99e3-90c209ae23ec",
    slug: "close_grip_bench_press",
    name: "Close-Grip Bench Press",
    biomechanical_instructions: {"setup":"Hands shoulder-width, elbows tucked.","eccentric":"Lower to lower sternum.","concentric":"Tricep-driven lockout.","safety":"Skip if wrist pain."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 4,
    default_reps: 8,
    movement_pattern: "push",
    primary_muscle: "triceps",
    synergist_muscles: ["chest","front_delts"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "wrist_stress",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "86554c79-aaa7-5913-854c-9e6572516f36",
    slug: "dumbbell_fly_flat",
    name: "Dumbbell Fly (Flat)",
    biomechanical_instructions: {"setup":"Slight elbow bend constant, supinated finish optional.","eccentric":"Open until chest stretch at bottom.","concentric":"Arc bells up; squeeze without clashing.","safety":"Moderate load only."},
    equipment_required: ["dumbbells","full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "chest",
    synergist_muscles: ["front_delts"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "shoulder_impingement_risk",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "b3166960-5761-5f0f-a2f1-e28170685b2e",
    slug: "landmine_press",
    name: "Landmine Press",
    biomechanical_instructions: {"setup":"Bar in corner, staggered stance, core braced.","eccentric":"Lower to chest with neutral shoulder path.","concentric":"Press on arc; scapular upward rotation friendly.","safety":"Good when overhead pressing irritates shoulder."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 4,
    default_reps: 10,
    movement_pattern: "push",
    primary_muscle: "upper_chest",
    synergist_muscles: ["front_delts","core","triceps"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "b038f967-06fb-5fd4-ba2e-469de94167c7",
    slug: "iliac_lat_pulldown",
    name: "Iliac Lat Pulldown",
    biomechanical_instructions: {"setup":"Lean back slightly, grip wide, pull to upper abs/iliac crest line.","eccentric":"3s return maintaining lat tension.","concentric":"Elbows drive down and back — lat not bicep.","safety":"Avoid behind-neck variant."},
    equipment_required: ["full_gym"],
    default_sets: 4,
    default_reps: 10,
    movement_pattern: "pull",
    primary_muscle: "lats",
    synergist_muscles: ["mid_back","biceps","rear_delts"],
    cns_fatigue_cost: 2,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "d00d1dcf-ad5b-5168-8113-97bd530ae60f",
    slug: "chest_supported_row",
    name: "Chest-Supported T-Bar Row",
    biomechanical_instructions: {"setup":"Chest on pad, neutral spine, pull to lower ribs.","eccentric":"3s lower without losing thoracic position.","concentric":"Elbows to hips; pause at contraction.","safety":"Removes lumbar from row equation."},
    equipment_required: ["full_gym"],
    default_sets: 4,
    default_reps: 10,
    movement_pattern: "pull",
    primary_muscle: "mid_back",
    synergist_muscles: ["lats","rear_delts","biceps"],
    cns_fatigue_cost: 2,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "505e009d-4581-57a3-98dd-107f7b3c4cda",
    slug: "pendlay_row",
    name: "Pendlay Row",
    biomechanical_instructions: {"setup":"Torso parallel floor each rep, bar on floor reset.","eccentric":"Dead stop on floor.","concentric":"Explosive pull to sternum.","safety":"Brace hard; not for acute lumbar issues."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 4,
    default_reps: 8,
    movement_pattern: "pull",
    primary_muscle: "mid_back",
    synergist_muscles: ["lats","rear_delts","erectors"],
    cns_fatigue_cost: 4,
    joint_stress_profile: "lumbar_shear",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "f0730633-bd57-5ffb-9489-c13a3b3e2071",
    slug: "t_bar_row",
    name: "T-Bar Row",
    biomechanical_instructions: {"setup":"Hinge stable, handle to sternum, avoid shrugging.","eccentric":"3s lower with control.","concentric":"Squeeze mid-back at top.","safety":"Use chest support variant if lumbar tired."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 4,
    default_reps: 10,
    movement_pattern: "pull",
    primary_muscle: "mid_back",
    synergist_muscles: ["lats","biceps","erectors"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "lumbar_shear",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "3c8992b5-1025-53aa-a298-f4e285ba5c40",
    slug: "dumbbell_row",
    name: "Single-Arm Dumbbell Row",
    biomechanical_instructions: {"setup":"Bench support, flat back, pull elbow to hip.","eccentric":"3s lower without shoulder roll.","concentric":"Lat-driven; pause at top.","safety":"No thoracic rotation."},
    equipment_required: ["dumbbells","full_gym"],
    default_sets: 4,
    default_reps: 10,
    movement_pattern: "pull",
    primary_muscle: "lats",
    synergist_muscles: ["mid_back","biceps","rear_delts"],
    cns_fatigue_cost: 2,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "e8b81325-eb74-59b4-af4b-ca018eed50b2",
    slug: "neutral_grip_pull_up",
    name: "Neutral-Grip Pull-Up",
    biomechanical_instructions: {"setup":"Handles parallel, dead hang, depress scapulae.","eccentric":"4s lower, shoulders down.","concentric":"Chest toward handles; elbows to ribs.","regression":"Band assist."},
    equipment_required: ["pull_up_bar","full_gym"],
    default_sets: 4,
    default_reps: 6,
    movement_pattern: "pull",
    primary_muscle: "lats",
    synergist_muscles: ["biceps","mid_back","core"],
    cns_fatigue_cost: 4,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "af6f89fe-5106-5296-a733-e31eb914f4ac",
    slug: "pull_up_overhand",
    name: "Pull-Up (Overhand)",
    biomechanical_instructions: {"setup":"Dead hang, hollow brace, lats engaged.","eccentric":"4s lower without shrug.","concentric":"Chest toward bar.","regression":"Band assist or pulldown."},
    equipment_required: ["pull_up_bar","bodyweight","full_gym"],
    default_sets: 4,
    default_reps: 6,
    movement_pattern: "pull",
    primary_muscle: "lats",
    synergist_muscles: ["biceps","mid_back"],
    cns_fatigue_cost: 4,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "f1564faf-d569-5e1d-8e09-1587fc89dafd",
    slug: "cable_pull_over",
    name: "Cable Pullover",
    biomechanical_instructions: {"setup":"Rope or bar, slight elbow bend, hips stable.","eccentric":"Arc overhead until lat stretch.","concentric":"Sweep down to hips — lat isolation.","safety":"Light load; rib flare controlled."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "lats",
    synergist_muscles: ["chest","triceps"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "ea8c2584-a1db-56ce-8afd-72b57d4462fc",
    slug: "cable_lateral_raise",
    name: "Cable Lateral Raise",
    biomechanical_instructions: {"setup":"Cable crosses behind body, soft elbows, lead with elbows.","eccentric":"3s lower without trap takeover.","concentric":"Raise to shoulder height; constant tension.","safety":"No swinging."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 15,
    movement_pattern: "isolation",
    primary_muscle: "side_delts",
    synergist_muscles: ["traps"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "34ec08d1-2f73-5c21-92b3-c0aaaf68d258",
    slug: "reverse_pec_deck",
    name: "Reverse Pec Deck",
    biomechanical_instructions: {"setup":"Chest on pad, arms parallel floor, rear delt line.","eccentric":"3s open to stretch.","concentric":"Sweep back; pause squeeze.","safety":"Avoid if posterior shoulder acute pain."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 15,
    movement_pattern: "isolation",
    primary_muscle: "rear_delts",
    synergist_muscles: ["mid_back","traps"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "161e809d-d896-58af-a36f-6e5e622ec369",
    slug: "face_pull",
    name: "Face Pull",
    biomechanical_instructions: {"setup":"Rope at face height, external rotate at end.","eccentric":"3s return without losing posture.","concentric":"Pull to forehead; spread rope.","safety":"Rotator cuff health staple."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 15,
    movement_pattern: "isolation",
    primary_muscle: "rear_delts",
    synergist_muscles: ["traps","rotator_cuff"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "rotator_cuff_heavy",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "5435cfa1-44d5-579c-bb05-a51aca571f13",
    slug: "machine_shoulder_press",
    name: "Machine Shoulder Press",
    biomechanical_instructions: {"setup":"Handles neutral, back flat, core braced.","eccentric":"3s lower to ear level.","concentric":"Press without excessive lean.","safety":"Skip if impingement active."},
    equipment_required: ["full_gym"],
    default_sets: 4,
    default_reps: 10,
    movement_pattern: "push",
    primary_muscle: "front_delts",
    synergist_muscles: ["triceps","upper_chest"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "rotator_cuff_heavy",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "3ba321a9-8282-5205-9c6c-d2a8c0db235e",
    slug: "bayesian_curl",
    name: "Bayesian Cable Curl",
    biomechanical_instructions: {"setup":"Cable behind body, arm behind torso line — long-head bias.","eccentric":"3s to full elbow extension behind plane.","concentric":"Curl without shoulder swinging forward.","safety":"Prime stretch-mediated biceps stimulus."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "biceps",
    synergist_muscles: ["forearms"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "389151a5-5db2-5d9a-babe-5176f34ed6cd",
    slug: "spider_curl",
    name: "Spider Curl (Incline Bench)",
    biomechanical_instructions: {"setup":"Chest on pad, arms hang vertical, shoulders fixed.","eccentric":"3s lower to near-full extension.","concentric":"Curl without shoulder drift.","safety":"Strict form; no hip drive."},
    equipment_required: ["dumbbells","full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "biceps",
    synergist_muscles: ["forearms"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "4becfce4-e8eb-58d5-94ca-9cd5c22f429e",
    slug: "preacher_curl_machine",
    name: "Preacher Curl (Machine)",
    biomechanical_instructions: {"setup":"Armpits at pad top, triceps on pad, wrists neutral.","eccentric":"3s to near-full stretch at bottom.","concentric":"Curl without lifting elbows off pad.","safety":"Avoid if distal biceps irritation."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "biceps",
    synergist_muscles: ["forearms"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "66732c4d-b198-5eed-a3a1-5b2df13ee5db",
    slug: "hammer_curl_incline",
    name: "Incline Hammer Curl",
    biomechanical_instructions: {"setup":"Bench 45°, arms hang, neutral grip.","eccentric":"3s lower behind torso line.","concentric":"Curl to shoulder; brachialis bias.","safety":"Do not swing torso."},
    equipment_required: ["dumbbells","full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "biceps",
    synergist_muscles: ["forearms","brachialis"],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "099bbb3a-6177-52ee-be10-bdc57052d03b",
    slug: "tricep_rope_pushdown",
    name: "Tricep Rope Pushdown",
    biomechanical_instructions: {"setup":"Elbows pinned to sides, slight forward lean.","eccentric":"3s up without shoulder migration.","concentric":"Split rope at lockout; lateral head bias.","safety":"Keep wrists neutral."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "triceps",
    synergist_muscles: [],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "9e3fb323-f5ac-5f98-bf0d-b330193e7397",
    slug: "ez_bar_skullcrusher",
    name: "EZ-Bar Skullcrusher",
    biomechanical_instructions: {"setup":"Bench, arms vertical, elbows point to ceiling.","eccentric":"Lower to forehead or behind head for stretch.","concentric":"Extend without flaring elbows.","safety":"Light-moderate load; elbow friendly path."},
    equipment_required: ["barbell","full_gym"],
    default_sets: 3,
    default_reps: 10,
    movement_pattern: "isolation",
    primary_muscle: "triceps",
    synergist_muscles: [],
    cns_fatigue_cost: 2,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "c51e7b7d-5086-566e-a4fb-c7f4a72e65f5",
    slug: "smith_machine_split_squat",
    name: "Smith Machine Split Squat",
    biomechanical_instructions: {"setup":"Staggered stance under bar, front shin near vertical at bottom.","eccentric":"3s lower; torso tall.","concentric":"Front heel drive.","safety":"Stable option vs free-weight BSS when fatigued."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 10,
    movement_pattern: "lunge",
    primary_muscle: "quadriceps",
    synergist_muscles: ["glutes"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "moderate_knee_stress",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "ced5ecda-f819-5421-b532-230b91962215",
    slug: "single_leg_leg_press",
    name: "Single-Leg Leg Press",
    biomechanical_instructions: {"setup":"Foot mid-platform, hip square, unilateral load.","eccentric":"3s lower without pelvis rotation.","concentric":"Press through mid-foot; fix asymmetries.","safety":"Do not lock knee aggressively."},
    equipment_required: ["full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "squat",
    primary_muscle: "quadriceps",
    synergist_muscles: ["glutes","adductors"],
    cns_fatigue_cost: 2,
    joint_stress_profile: "moderate_knee_stress",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "389b74f5-bcd3-5a93-80b9-5d8f662f60ab",
    slug: "walking_lunge",
    name: "Walking Lunge",
    biomechanical_instructions: {"setup":"Torso tall, long stride, dumbbells at sides optional.","eccentric":"Soft rear knee touch.","concentric":"Drive front heel; alternate.","safety":"Clear path; control knee valgus."},
    equipment_required: ["dumbbells","bodyweight","full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "lunge",
    primary_muscle: "quadriceps",
    synergist_muscles: ["glutes","adductors"],
    cns_fatigue_cost: 3,
    joint_stress_profile: "moderate_knee_stress",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "3ba03b0a-00ef-5e43-9baf-354c0ef4a932",
    slug: "seated_calf_raise",
    name: "Seated Calf Raise",
    biomechanical_instructions: {"setup":"Pad on knees, balls of feet on edge, full stretch at bottom.","eccentric":"3s lower to soleus stretch.","concentric":"Rise to peak; pause.","safety":"Soleus-biased hypertrophy."},
    equipment_required: ["full_gym"],
    default_sets: 4,
    default_reps: 15,
    movement_pattern: "isolation",
    primary_muscle: "calves",
    synergist_muscles: [],
    cns_fatigue_cost: 1,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "83dde898-2b40-596a-90b0-798e7ac920ce",
    slug: "standing_calf_raise",
    name: "Standing Calf Raise",
    biomechanical_instructions: {"setup":"Gastrocnemius bias — legs straight, full ROM.","eccentric":"3s lower to stretch.","concentric":"Peak contraction at top.","safety":"Use machine or step for ROM."},
    equipment_required: ["full_gym","bodyweight"],
    default_sets: 4,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "calves",
    synergist_muscles: [],
    cns_fatigue_cost: 2,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
  {
    id: "882154ba-c52d-5f5f-b463-5d4dc1482b92",
    slug: "dumbbell_shrug",
    name: "Dumbbell Shrug",
    biomechanical_instructions: {"setup":"Arms straight, traps set, no rolling.","eccentric":"3s lower fully.","concentric":"Shrug straight up; pause.","safety":"Avoid if cervical issues."},
    equipment_required: ["dumbbells","full_gym"],
    default_sets: 3,
    default_reps: 12,
    movement_pattern: "isolation",
    primary_muscle: "traps",
    synergist_muscles: ["forearms"],
    cns_fatigue_cost: 2,
    joint_stress_profile: "cervical_load",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "04e5d706-4342-50c3-bd35-4ebe922c9f68",
    slug: "overhead_press",
    name: "Standing Overhead Press",
    biomechanical_instructions: {"setup":"Rack grip, glutes tight, ribs down, chin back.","eccentric":"Bar to clavicle without excessive lean.","concentric":"Press vertical; head through at lockout.","safety":"Skip if active impingement."},
    equipment_required: ["barbell","dumbbells","full_gym"],
    default_sets: 4,
    default_reps: 8,
    movement_pattern: "push",
    primary_muscle: "front_delts",
    synergist_muscles: ["triceps","upper_chest","core"],
    cns_fatigue_cost: 4,
    joint_stress_profile: "rotator_cuff_heavy",
    stretch_mediated_hypertrophy: false,
  },
  {
    id: "a6f9d0a6-ef64-5f6e-aa47-b42b9c17c892",
    slug: "push_up",
    name: "Push-Up (Deficit Optional)",
    biomechanical_instructions: {"setup":"Hands under shoulders, full plank, optional handles for depth.","eccentric":"3s lower, chest stretch at bottom.","concentric":"Press to lockout.","regression":"Incline push-up."},
    equipment_required: ["bodyweight"],
    default_sets: 4,
    default_reps: 12,
    movement_pattern: "push",
    primary_muscle: "chest",
    synergist_muscles: ["triceps","front_delts","core"],
    cns_fatigue_cost: 2,
    joint_stress_profile: "low_impact",
    stretch_mediated_hypertrophy: true,
  },
];

export const ELITE_EXERCISE_COUNT = ELITE_EXERCISES.length;
