/**
 * Runtime PT-BR dictionary for Elite biomechanical cues.
 * Applied by cueMapper — do not mutate seed_hypertrophy.sql / eliteCatalog.ts.
 */

export const ELITE_CUE_PT_BR: Readonly<Record<string, string>> = Object.freeze({
  "Front foot on 2–4\" deficit, rear foot elevated, torso slight forward for quad bias.": "Pé da frente em déficit de 5–10 cm, pé de trás elevado, tronco levemente à frente para ênfase no quadríceps.",
  "3s lower until rear knee nears floor; front knee tracks over mid-foot.": "Desça em 3s até o joelho de trás quase tocar o chão; joelho da frente acompanha o meio do pé.",
  "Drive through front heel; minimize push from back leg.": "Empurre pelo calcanhar da frente; minimize a impulsão da perna de trás.",
  "Reduce deficit if knee shear pain; hold dumbbells at sides for balance.": "Reduza o déficit se houver dor de cisalhamento no joelho; segure halteres ao lado para equilíbrio.",
  "Feet mid-platform, back flat on pad, knees align with toes.": "Pés no meio da plataforma, costas planas no encosto, joelhos alinhados aos dedos.",
  "Controlled 2–3s to deep knee flexion without pelvis tuck.": "2–3s controlados até flexão profunda do joelho sem retroversão pélvica.",
  "Press through mid-foot; avoid locking knees violently.": "Pressione pelo meio do pé; evite travar os joelhos com violência.",
  "Limit depth if lumbar rounds off pad.": "Limite a profundidade se a lombar arredondar fora do encosto.",
  "Shoulders under pads, feet low on platform for quad emphasis.": "Ombros sob as almofadas, pés baixos na plataforma para ênfase no quadríceps.",
  "Let arc guide depth; keep ribs stacked.": "Deixe o arco guiar a profundidade; mantenha as costelas alinhadas.",
  "Drive knees forward over toes; constant tension arc.": "Projete os joelhos sobre os dedos; arco de tensão constante.",
  "Stop above pain-limited ROM.": "Pare acima da amplitude limitada pela dor.",
  "Belt at hips, hold straps, upright torso, feet shoulder-width.": "Cinto nos quadris, segure as alças, tronco ereto, pés na largura dos ombros.",
  "Sit between hips without spinal compression.": "Sente entre os quadris sem compressão da coluna.",
  "Drive floor; glutes and quads without axial load.": "Empurre o chão; glúteos e quadríceps sem carga axial.",
  "Ideal when low-back fatigue is high.": "Ideal quando a fadiga lombar está alta.",
  "High-bar or low-bar, brace 360°, heels hip-width.": "High-bar ou low-bar, brace 360°, calcanhares na largura do quadril.",
  "Sit between hips; knees track toes; neutral spine.": "Sente entre os quadris; joelhos acompanham os dedos; coluna neutra.",
  "Drive floor; hips and chest rise together.": "Empurre o chão; quadril e peito sobem juntos.",
  "Safety bars set; avoid valgus collapse.": "Barras de segurança ajustadas; evite colapso em valgo.",
  "Heels elevated or anchored, hips extended, torso lean.": "Calcanhares elevados ou ancorados, quadril estendido, tronco inclinado.",
  "3s knee flexion with hips open — pure quad lengthening.": "3s de flexão de joelho com quadril aberto — alongamento puro de quadríceps.",
  "Extend knees without hip closure.": "Estenda os joelhos sem fechar o quadril.",
  "Use band assist if patellar irritation.": "Use assistência com elástico se houver irritação patelar.",
  "Pad at ankle, femur neutral, back flat on seat.": "Almofada no tornozelo, fêmur neutro, costas planas no assento.",
  "3s lower without hip lift off seat.": "Desça em 3s sem levantar o quadril do assento.",
  "Extend to peak contraction; pause 1s.": "Estenda até o pico de contração; pause 1s.",
  "Avoid if active patellar tendinopathy.": "Evite se houver tendinopatia patelar ativa.",
  "Pad above heels, hips pinned, dorsiflex ankles optional.": "Almofada acima dos calcanhares, quadril fixo, dorsiflexão opcional.",
  "3s lower to full hamstring stretch.": "Desça em 3s até o alongamento completo dos isquiotibiais.",
  "Curl without lifting hips.": "Faça a rosca sem levantar o quadril.",
  "Control tempo — avoid ballistic reps.": "Controle o tempo — evite repetições balísticas.",
  "Ankles fixed, tall line knee to shoulder.": "Tornozelos fixos, linha alta do joelho ao ombro.",
  "Lower as slow as possible using hamstrings as brakes.": "Desça o mais lento possível usando os isquiotibiais como freio.",
  "Push lightly from floor if needed.": "Empurre levemente o chão se necessário.",
  "Band assist at chest.": "Assistência com elástico no peito.",
  "Soft knee bend, bar close to legs, lats engaged, ribs down.": "Joelhos levemente flexionados, barra perto das pernas, dorsais ativos, costelas baixas.",
  "Hinge until hamstrings peak stretch; shins near vertical.": "Faça a dobradiça até o pico de alongamento dos isquiotibiais; canelas quase verticais.",
  "Glute drive; bar skims thighs.": "Empurre com o glúteo; barra raspa as coxas.",
  "Stop if lumbar flexion appears.": "Pare se aparecer flexão lombar.",
  "Soft knee bend, bells close to thighs, neutral spine.": "Joelhos levemente flexionados, halteres perto das coxas, coluna neutra.",
  "Hinge to hamstring end-range; feel stretch at bottom.": "Faça a dobradiça até o fim dos isquiotibiais; sinta o alongamento na base.",
  "Squeeze glutes; avoid hyperextension.": "Contraia os glúteos; evite hiperextensão.",
  "Reduce load if grip limits set before hamstrings.": "Reduza a carga se a pegada limitar a série antes dos isquiotibiais.",
  "Minimal knee bend, bar over mid-foot, hinge from hips.": "Flexão mínima de joelho, barra sobre o meio do pé, dobradiça pelo quadril.",
  "Bar tracks close; maximize hamstring length.": "Barra próxima ao corpo; maximize o alongamento dos isquiotibiais.",
  "Hip extension without back hyperextension.": "Extensão de quadril sem hiperextensão lombar.",
  "Lighter than RDL if lumbar fatigue high.": "Mais leve que o RDL se a fadiga lombar estiver alta.",
  "Mid-foot bar, hinge, lats on, neutral neck.": "Barra no meio do pé, dobradiça, dorsais ativos, pescoço neutro.",
  "Controlled lower or reset per block.": "Descida controlada ou reset por bloco.",
  "Floor push, hips through, glutes lock.": "Empurre o chão, quadril à frente, trave os glúteos.",
  "No rounding; treat as high CNS day.": "Sem arredondar; trate como dia de alto CNS.",
  "Bar at just below knee, wedge, lats tight.": "Barra logo abaixo do joelho, calço, dorsais ativos.",
  "Lower to pins with control.": "Desça até os pinos com controle.",
  "Lock hips; overload posterior chain.": "Trave o quadril; sobrecarregue a cadeia posterior.",
  "Use when deadlift fatigue is managed separately.": "Use quando a fadiga do deadlift for gerida à parte.",
  "Bar on back like squat, soft knees, brace hard.": "Barra nas costas como no agachamento, joelhos suaves, brace firme.",
  "Hinge until hamstrings limit ROM.": "Faça a dobradiça até os isquiotibiais limitarem a amplitude.",
  "Glute-ham drive to stand.": "Empurre com glúteo e posteriores para ficar em pé.",
  "Light load; advanced athletes only.": "Carga leve; apenas atletas avançados.",
  "Upper back on bench, bar padded, chin tucked, ribs down.": "Parte superior das costas no banco, barra acolchoada, queixo recolhido, costelas baixas.",
  "Lower until stretch at bottom without lumbar arch.": "Desça até o alongamento na base sem arquear a lombar.",
  "Full glute lockout; shins vertical at top.": "Bloqueio final completo de glúteo; canelas verticais no topo.",
  "Pause at top; avoid cervical hyperextension.": "Pause no topo; evite hiperextensão cervical.",
  "Ankle strap, slight forward lean, squeeze at top.": "Cinta no tornozelo, leve inclinação à frente, contraia no topo.",
  "3s return without spinal rotation.": "Retorne em 3s sem rotacionar a coluna.",
  "Extend hip behind body; glute-only path.": "Estenda o quadril atrás do corpo; trajetória só de glúteo.",
  "Avoid excessive lumbar extension.": "Evite extensão lombar excessiva.",
  "Bench 30° — clavicular head bias; feet planted, scapulae retracted.": "Banco a 30° — ênfase na cabeça clavicular; pés plantados, escápulas retraídas.",
  "3s to upper chest line; elbows 45°.": "3s até a linha do peito superior; cotovelos a 45°.",
  "Press up and slightly in; dumbbells independent path.": "Pressione para cima e levemente para dentro; trajetória independente dos halteres.",
  "30° reduces impingement vs steep incline.": "30° reduz impacto vs. inclinação mais íngreme.",
  "Bench 30°, cables low, slight elbow bend fixed.": "Banco a 30°, cabos baixos, leve flexão de cotovelo fixa.",
  "Arc down until upper chest stretch.": "Arqueie para baixo até alongar o peito superior.",
  "Sweep up on fiber line; constant tension.": "Varra para cima na linha das fibras; tensão constante.",
  "Light-moderate load; stretch is the stimulus.": "Carga leve a moderada; o alongamento é o estímulo.",
  "Feet flat, arch legal, wrists over elbows, scapulae pinned.": "Pés firmes no chão, arco plantar permitido, punhos sobre os cotovelos, escápulas retraídas.",
  "3s to mid-chest.": "3s até o meio do peito.",
  "Leg drive, press to lockout.": "Impulsione com as pernas e pressione até o bloqueio final.",
  "Spotter or safeties.": "Use parceiro de segurança ou barras de segurança.",
  "Hands shoulder-width, elbows tucked.": "Mãos na largura dos ombros, cotovelos juntos ao corpo.",
  "Lower to lower sternum.": "Desça até o esterno inferior.",
  "Tricep-driven lockout.": "Bloqueio final guiado pelo tríceps.",
  "Skip if wrist pain.": "Pule se houver dor no punho.",
  "Slight elbow bend constant, supinated finish optional.": "Leve flexão constante de cotovelo; finalização supinada opcional.",
  "Open until chest stretch at bottom.": "Abra até alongar o peito na base.",
  "Arc bells up; squeeze without clashing.": "Arqueie os halteres para cima; contraia sem bater um no outro.",
  "Moderate load only.": "Apenas carga moderada.",
  "Bar in corner, staggered stance, core braced.": "Barra no canto, base escalonada, core braceado.",
  "Lower to chest with neutral shoulder path.": "Desça até o peito com trajetória neutra de ombro.",
  "Press on arc; scapular upward rotation friendly.": "Pressione em arco; amigável à rotação ascendente da escápula.",
  "Good when overhead pressing irritates shoulder.": "Bom quando o desenvolvimento irrita o ombro.",
  "Lean back slightly, grip wide, pull to upper abs/iliac crest line.": "Incline levemente para trás, pegada larga, puxe até a linha do abdômen superior/crista ilíaca.",
  "3s return maintaining lat tension.": "Retorne em 3s mantendo tensão no dorsal.",
  "Elbows drive down and back — lat not bicep.": "Cotovelos descem e vão para trás — dorsal, não bíceps.",
  "Avoid behind-neck variant.": "Evite a variação atrás do pescoço.",
  "Chest on pad, neutral spine, pull to lower ribs.": "Peito na almofada, coluna neutra, puxe até as costelas inferiores.",
  "3s lower without losing thoracic position.": "Desça em 3s sem perder a posição torácica.",
  "Elbows to hips; pause at contraction.": "Cotovelos aos quadris; pause na contração.",
  "Removes lumbar from row equation.": "Tira a lombar da equação da remada.",
  "Torso parallel floor each rep, bar on floor reset.": "Tronco paralelo ao chão a cada rep, barra reseta no chão.",
  "Dead stop on floor.": "Parada total no chão.",
  "Explosive pull to sternum.": "Puxada explosiva até o esterno.",
  "Brace hard; not for acute lumbar issues.": "Braceie com firmeza; não indicado para lombalgia aguda.",
  "Hinge stable, handle to sternum, avoid shrugging.": "Dobradiça estável, alça até o esterno, evite encolher ombros.",
  "3s lower with control.": "Desça em 3s com controle.",
  "Squeeze mid-back at top.": "Contraia o meio das costas no topo.",
  "Use chest support variant if lumbar tired.": "Use a variação com apoio de peito se a lombar estiver cansada.",
  "Bench support, flat back, pull elbow to hip.": "Apoio no banco, costas planas, puxe o cotovelo ao quadril.",
  "3s lower without shoulder roll.": "Desça em 3s sem rolar o ombro.",
  "Lat-driven; pause at top.": "Movimento guiado pelo dorsal; pause no topo.",
  "No thoracic rotation.": "Sem rotação torácica.",
  "Handles parallel, dead hang, depress scapulae.": "Alças paralelas, pendurado passivo, abaixe as escápulas.",
  "4s lower, shoulders down.": "Desça em 4s, ombros baixos.",
  "Chest toward handles; elbows to ribs.": "Peito em direção às alças; cotovelos às costelas.",
  "Band assist.": "Assistência com elástico.",
  "Dead hang, hollow brace, lats engaged.": "Pendurado passivo, brace hollow, dorsais engajados.",
  "4s lower without shrug.": "Desça em 4s sem encolher os ombros.",
  "Chest toward bar.": "Peito em direção à barra.",
  "Band assist or pulldown.": "Assistência com elástico ou pulley.",
  "Rope or bar, slight elbow bend, hips stable.": "Corda ou barra, leve flexão de cotovelo, quadril estável.",
  "Arc overhead until lat stretch.": "Arqueie acima da cabeça até alongar o dorsal.",
  "Sweep down to hips — lat isolation.": "Varra para baixo até o quadril — isolamento de dorsal.",
  "Light load; rib flare controlled.": "Carga leve; controle a abertura das costelas.",
  "Cable crosses behind body, soft elbows, lead with elbows.": "Cabo cruza atrás do corpo, cotovelos suaves, lidere com os cotovelos.",
  "3s lower without trap takeover.": "Desça em 3s sem deixar o trapézio dominar.",
  "Raise to shoulder height; constant tension.": "Eleve até a altura do ombro; tensão constante.",
  "No swinging.": "Sem balanço.",
  "Chest on pad, arms parallel floor, rear delt line.": "Peito na almofada, braços paralelos ao chão, linha do deltóide posterior.",
  "3s open to stretch.": "Abra em 3s até o alongamento.",
  "Sweep back; pause squeeze.": "Varra para trás; pause e contraia.",
  "Avoid if posterior shoulder acute pain.": "Evite se houver dor aguda no ombro posterior.",
  "Rope at face height, external rotate at end.": "Corda na altura do rosto, rotação externa no final.",
  "3s return without losing posture.": "Retorne em 3s sem perder a postura.",
  "Pull to forehead; spread rope.": "Puxe até a testa; abra a corda.",
  "Rotator cuff health staple.": "Exercício-base para saúde do manguito rotador.",
  "Handles neutral, back flat, core braced.": "Alças neutras, costas planas, core braceado.",
  "3s lower to ear level.": "Desça em 3s até a altura da orelha.",
  "Press without excessive lean.": "Pressione sem inclinar demais.",
  "Skip if impingement active.": "Pule se o impacto estiver ativo.",
  "Cable behind body, arm behind torso line — long-head bias.": "Cabo atrás do corpo, braço atrás da linha do tronco — ênfase na cabeça longa.",
  "3s to full elbow extension behind plane.": "3s até extensão completa do cotovelo atrás do plano.",
  "Curl without shoulder swinging forward.": "Faça a rosca sem balançar o ombro à frente.",
  "Prime stretch-mediated biceps stimulus.": "Estímulo principal de bíceps mediado por alongamento.",
  "Chest on pad, arms hang vertical, shoulders fixed.": "Peito na almofada, braços pendentes na vertical, ombros fixos.",
  "3s lower to near-full extension.": "Desça em 3s até quase extensão completa.",
  "Curl without shoulder drift.": "Faça a rosca sem deixar o ombro migrar.",
  "Strict form; no hip drive.": "Forma estrita; sem impulsão de quadril.",
  "Armpits at pad top, triceps on pad, wrists neutral.": "Axilas no topo da almofada, tríceps apoiados, punhos neutros.",
  "3s to near-full stretch at bottom.": "3s até quase alongamento completo na base.",
  "Curl without lifting elbows off pad.": "Faça a rosca sem levantar os cotovelos da almofada.",
  "Avoid if distal biceps irritation.": "Evite se houver irritação distal do bíceps.",
  "Bench 45°, arms hang, neutral grip.": "Banco a 45°, braços pendentes, pegada neutra.",
  "3s lower behind torso line.": "Desça em 3s atrás da linha do tronco.",
  "Curl to shoulder; brachialis bias.": "Faça a rosca até o ombro; ênfase no braquial.",
  "Do not swing torso.": "Não balance o tronco.",
  "Elbows pinned to sides, slight forward lean.": "Cotovelos colados ao corpo, leve inclinação à frente.",
  "3s up without shoulder migration.": "Suba em 3s sem migrar o ombro.",
  "Split rope at lockout; lateral head bias.": "Abra a corda no bloqueio final; ênfase na cabeça lateral.",
  "Keep wrists neutral.": "Mantenha os punhos neutros.",
  "Bench, arms vertical, elbows point to ceiling.": "Banco, braços verticais, cotovelos apontando ao teto.",
  "Lower to forehead or behind head for stretch.": "Desça até a testa ou atrás da cabeça para alongar.",
  "Extend without flaring elbows.": "Estenda sem abrir os cotovelos.",
  "Light-moderate load; elbow friendly path.": "Carga leve a moderada; trajetória amigável ao cotovelo.",
  "Staggered stance under bar, front shin near vertical at bottom.": "Base escalonada sob a barra, canela da frente quase vertical na base.",
  "3s lower; torso tall.": "Desça em 3s; tronco alto.",
  "Front heel drive.": "Empurre o calcanhar da frente.",
  "Stable option vs free-weight BSS when fatigued.": "Opção estável vs. afundo búlgaro livre quando fatigado.",
  "Foot mid-platform, hip square, unilateral load.": "Pé no meio da plataforma, quadril alinhado, carga unilateral.",
  "3s lower without pelvis rotation.": "Desça em 3s sem rotacionar a pelve.",
  "Press through mid-foot; fix asymmetries.": "Pressione pelo meio do pé; corrija assimetrias.",
  "Do not lock knee aggressively.": "Não trave o joelho de forma agressiva.",
  "Torso tall, long stride, dumbbells at sides optional.": "Tronco alto, passada longa, halteres ao lado opcionais.",
  "Soft rear knee touch.": "Toque suave do joelho de trás.",
  "Drive front heel; alternate.": "Empurre o calcanhar da frente; alterne.",
  "Clear path; control knee valgus.": "Mantenha trajetória limpa; controle o valgo do joelho.",
  "Pad on knees, balls of feet on edge, full stretch at bottom.": "Almofada nos joelhos, metatarsos na borda, alongamento completo na base.",
  "3s lower to soleus stretch.": "Desça em 3s até o alongamento do sóleo.",
  "Rise to peak; pause.": "Suba até o pico; pause.",
  "Soleus-biased hypertrophy.": "Hipertrofia com ênfase no sóleo.",
  "Gastrocnemius bias — legs straight, full ROM.": "Ênfase no gastrocnêmio — pernas estendidas, amplitude completa.",
  "3s lower to stretch.": "Desça em 3s até o alongamento.",
  "Peak contraction at top.": "Pico de contração no topo.",
  "Use machine or step for ROM.": "Use máquina ou step para amplitude.",
  "Arms straight, traps set, no rolling.": "Braços estendidos, trapézios preparados, sem rolar.",
  "3s lower fully.": "Desça completamente em 3s.",
  "Shrug straight up; pause.": "Encolha reto para cima; pause.",
  "Avoid if cervical issues.": "Evite se houver problemas cervicais.",
  "Rack grip, glutes tight, ribs down, chin back.": "Pegada de rack, glúteos firmes, costelas baixas, queixo para trás.",
  "Bar to clavicle without excessive lean.": "Barra até a clavícula sem inclinar demais.",
  "Press vertical; head through at lockout.": "Pressione na vertical; passe a cabeça no bloqueio final.",
  "Skip if active impingement.": "Pule se houver impacto ativo.",
  "Hands under shoulders, full plank, optional handles for depth.": "Mãos sob os ombros, prancha completa, alças opcionais para profundidade.",
  "3s lower, chest stretch at bottom.": "Desça em 3s, alongando o peito na base.",
  "Press to lockout.": "Pressione até o bloqueio final.",
  "Incline push-up.": "Flexão inclinada.",
});

/** Exact-string translation of Elite / alias cue text to PT-BR. */
export function translateCueToPtBr(text: string): string {
  const trimmed = text.trim();
  if (!trimmed) return text;
  return ELITE_CUE_PT_BR[trimmed] ?? ELITE_CUE_PT_BR[text] ?? text;
}

