insert into public.library_exercises (
  id,
  slug,
  name,
  biomechanical_instructions,
  equipment_required,
  default_sets,
  default_reps,
  movement_pattern,
  primary_muscle,
  synergist_muscles,
  cns_fatigue_cost,
  joint_stress_profile,
  stretch_mediated_hypertrophy,
  visual_asset_url,
  visual_asset_type
) values
  (
    '01a12c7b-e06b-504b-9279-9a9a40f4d5ea'::uuid,
    'dumbbell_farmers_carry',
    'Dumbbell farmer''s carry',
    '{"merged_steps": ["Grab half your body weight in each hand and walk."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Grab half your body weight in each hand and walk."], "description": "Grab half your body weight in each hand and walk."}], "summary": "Grab half your body weight in each hand and walk.", "setup": "Grab half your body weight in each hand and walk."}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'general',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '117d6cdf-3eaa-59a1-9f78-5747e6999bba'::uuid,
    'dumbbell_floor_press',
    'Dumbbell Floor Press',
    '{"merged_steps": ["Grab your dumbbells and lay flat on your back with your knees bent and your feet flat on the ground (use a bench if you have one).", "Press the weights up, locking out your elbows (A).", "Lower them slowly until your upper arms are resting on the floor (B) close to your body.", "Pause here before explosively pressing back up.", "Squeeze your chest hard and repeat."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Grab your dumbbells and lay flat on your back with your knees bent and your feet flat on the ground (use a bench if you have one).", "Press the weights up, locking out your elbows (A).", "Lower them slowly until your upper arms are resting on the floor (B) close to your body.", "Pause here before explosively pressing back up.", "Squeeze your chest hard and repeat."], "description": "Grab your dumbbells and lay flat on your back with your knees bent and your feet flat on the ground (use a bench if you have one). Press the weights up, locking out your elbows (A). Lower them slowly until your upper arms are resting on the floor (B) close to your body. Pause here before explosively pressing back up. Squeeze your chest hard and repeat."}], "summary": "Grab your dumbbells and lay flat on your back with your knees bent and your feet flat on the ground (use a bench if you have one). Press the weights up, locking out your elbows (A). Lower them slowly until your upper arms are resting on the floor (B) close to your body. Pause here before explosively pressing back up. Squeeze your chest hard and repeat.", "setup": "Grab your dumbbells and lay flat on your back with your knees bent and your feet flat on the ground (use a bench if you have one).", "eccentric": "Press the weights up, locking out your elbows (A).", "concentric": "Lower them slowly until your upper arms are resting on the floor (B) close to your body.", "regression": "Pause here before explosively pressing back up.", "safety": "Squeeze your chest hard and repeat."}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'chest',
    array['delts', 'biceps', 'triceps'],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '86d9b63e-97cd-54d9-a147-7db8f35bc9e9'::uuid,
    'dumbbell_fly',
    'dumbbell fly',
    '{"merged_steps": ["[''Lie flat on a bench with a dumbbell in each hand, palms facing each other.'', ''Extend your arms straight up over your chest, with a slight bend in your elbows.'', ''Keeping a slight bend in your elbows, lower your arms out to the sides in a wide arc until you feel a stretch in your chest.'', ''Pause for a moment, then reverse the movement and bring the dumbbells back up to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Lie flat on a bench with a dumbbell in each hand, palms facing each other.'', ''Extend your arms straight up over your chest, with a slight bend in your elbows.'', ''Keeping a slight bend in your elbows, lower your arms out to the sides in a wide arc until you feel a stretch in your chest.'', ''Pause for a moment, then reverse the movement and bring the dumbbells back up to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The dumbbell fly is a chest exercise performed lying on a bench, using dumbbells to stretch and contract the pectoral muscles through a wide arc motion."}], "summary": "The dumbbell fly is a chest exercise performed lying on a bench, using dumbbells to stretch and contract the pectoral muscles through a wide arc motion.", "setup": "[''Lie flat on a bench with a dumbbell in each hand, palms facing each other.'', ''Extend your arms straight up over your chest, with a slight bend in your elbows.'', ''Keeping a slight bend in your elbows, lower your arms out to the sides in a wide arc until you feel a stretch in your chest.'', ''Pause for a moment, then reverse the movement and bring the dumbbells back up to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'push',
    'chest',
    array['delts'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/308.0.gif',
    'gif'
  ),
  (
    '6019a9d5-b277-5f1f-a77b-1ee679f81479'::uuid,
    'dumbbell_frog_press',
    'Dumbbell Frog Press',
    '{"merged_steps": ["Similar to hip thrust, but with feet put up together, lifting the butt off the ground in a frog like position."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Similar to hip thrust, but with feet put up together, lifting the butt off the ground in a frog like position."], "description": "Similar to hip thrust, but with feet put up together, lifting the butt off the ground in a frog like position."}], "summary": "Similar to hip thrust, but with feet put up together, lifting the butt off the ground in a frog like position.", "setup": "Similar to hip thrust, but with feet put up together, lifting the butt off the ground in a frog like position."}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'glutes',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '48b49836-d671-5469-a8a6-a42025ce7da8'::uuid,
    'dumbbell_front_raise',
    'dumbbell front raise',
    '{"merged_steps": ["[''Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your thighs.'', ''Keeping your arms straight, exhale and lift the dumbbells in front of you until they are at shoulder level.'', ''Pause for a moment at the top, then inhale and slowly lower the dumbbells back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your thighs.'', ''Keeping your arms straight, exhale and lift the dumbbells in front of you until they are at shoulder level.'', ''Pause for a moment at the top, then inhale and slowly lower the dumbbells back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The dumbbell front raise is a shoulder exercise that targets the deltoid muscles, particularly the anterior (front) portion. It also engages the biceps and trapezius as secondary muscles. The movement involves lifting dumbbells in front of the body to shoulder height, focusing on controlled motion and proper form."}], "summary": "The dumbbell front raise is a shoulder exercise that targets the deltoid muscles, particularly the anterior (front) portion. It also engages the biceps and trapezius as secondary muscles. The movement involves lifting dumbbells in front of the body to shoulder height, focusing on controlled motion and proper form.", "setup": "[''Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your thighs.'', ''Keeping your arms straight, exhale and lift the dumbbells in front of you until they are at shoulder level.'', ''Pause for a moment at the top, then inhale and slowly lower the dumbbells back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'push',
    'delts',
    array['biceps', 'trapezius'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/310.0.gif',
    'gif'
  ),
  (
    'a8c714cd-44cb-51d5-b268-06b3f0e8e6b8'::uuid,
    'dumbbell_front_raise_v_2',
    'dumbbell front raise v. 2',
    '{"merged_steps": ["[''Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your thighs.'', ''Keep your back straight and engage your core.'', ''Slowly lift the dumbbells in front of you, with your arms straight, until they are at shoulder level.'', ''Pause for a moment at the top, then slowly lower the dumbbells back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your thighs.'', ''Keep your back straight and engage your core.'', ''Slowly lift the dumbbells in front of you, with your arms straight, until they are at shoulder level.'', ''Pause for a moment at the top, then slowly lower the dumbbells back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The dumbbell front raise v. 2 is a shoulder exercise that targets the deltoid muscles. It involves lifting dumbbells in front of the body to shoulder height, focusing on controlled movement and proper form."}], "summary": "The dumbbell front raise v. 2 is a shoulder exercise that targets the deltoid muscles. It involves lifting dumbbells in front of the body to shoulder height, focusing on controlled movement and proper form.", "setup": "[''Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your thighs.'', ''Keep your back straight and engage your core.'', ''Slowly lift the dumbbells in front of you, with your arms straight, until they are at shoulder level.'', ''Pause for a moment at the top, then slowly lower the dumbbells back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'push',
    'delts',
    array['trapezius', 'biceps'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/309.0.gif',
    'gif'
  ),
  (
    '62a0faf0-2820-5465-a765-837d1a1762dc'::uuid,
    'dumbbell_front_squat',
    'Dumbbell Front Squat',
    '{"merged_steps": ["This exercise involves holding a dumbbell in each hand at shoulder height and performing a squat.", "It targets the lower body muscles, including the quads, hamstrings, and glutes, while also engaging the core and upper body."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["This exercise involves holding a dumbbell in each hand at shoulder height and performing a squat.", "It targets the lower body muscles, including the quads, hamstrings, and glutes, while also engaging the core and upper body."], "description": "This exercise involves holding a dumbbell in each hand at shoulder height and performing a squat. It targets the lower body muscles, including the quads, hamstrings, and glutes, while also engaging the core and upper body."}], "summary": "This exercise involves holding a dumbbell in each hand at shoulder height and performing a squat. It targets the lower body muscles, including the quads, hamstrings, and glutes, while also engaging the core and upper body.", "setup": "This exercise involves holding a dumbbell in each hand at shoulder height and performing a squat.", "concentric": "It targets the lower body muscles, including the quads, hamstrings, and glutes, while also engaging the core and upper body."}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'glutes',
    array['delts', 'core'],
    4,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '99a77192-3e49-521b-b6d8-9a8bd9e21fe7'::uuid,
    'dumbbell_full_can_lateral_raise',
    'dumbbell full can lateral raise',
    '{"merged_steps": ["[''Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your body.'', ''Keep your back straight and engage your core.'', ''Raise your arms out to the sides, keeping a slight bend in your elbows, until they are parallel to the ground.'', ''Pause for a moment at the top, then slowly lower your arms back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your body.'', ''Keep your back straight and engage your core.'', ''Raise your arms out to the sides, keeping a slight bend in your elbows, until they are parallel to the ground.'', ''Pause for a moment at the top, then slowly lower your arms back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The dumbbell full can lateral raise is a shoulder exercise that targets the deltoids and also engages the traps and rotator cuff. It involves raising dumbbells to the sides with a slight bend in the elbows, mimicking the motion of pouring from a can, which helps reduce shoulder impingement risk."}], "summary": "The dumbbell full can lateral raise is a shoulder exercise that targets the deltoids and also engages the traps and rotator cuff. It involves raising dumbbells to the sides with a slight bend in the elbows, mimicking the motion of pouring from a can, which helps reduce shoulder impingement risk.", "setup": "[''Stand with your feet shoulder-width apart, holding a dumbbell in each hand with your palms facing your body.'', ''Keep your back straight and engage your core.'', ''Raise your arms out to the sides, keeping a slight bend in your elbows, until they are parallel to the ground.'', ''Pause for a moment at the top, then slowly lower your arms back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'push',
    'delts',
    array['traps', 'rotator_cuff'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/311.0.gif',
    'gif'
  ),
  (
    'a03f1586-c18b-5404-bb26-fb57160447b7'::uuid,
    'dumbbell_goblet_squat',
    'Dumbbell Goblet Squat',
    '{"merged_steps": ["Grasp dumbbell with both hands at the sides of the upper plates.", "Hold dumbbell in front of chest, close to torso.", "Place feet about shoulderwide apart, keep knees slightly bent.", "Squat down until thighs are parallel to floor.", "Keep back straight, bend and move hips backward to keep knees above feet.", "Return, keep knees slightly flexed.", "Repeat.", "Keep bodyweight on heels and look ahead or slightly above to keep back straight."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Grasp dumbbell with both hands at the sides of the upper plates.", "Hold dumbbell in front of chest, close to torso.", "Place feet about shoulderwide apart, keep knees slightly bent.", "Squat down until thighs are parallel to floor.", "Keep back straight, bend and move hips backward to keep knees above feet.", "Return, keep knees slightly flexed.", "Repeat.", "Keep bodyweight on heels and look ahead or slightly above to keep back straight."], "description": "Grasp dumbbell with both hands at the sides of the upper plates. Hold dumbbell in front of chest, close to torso. Place feet about shoulderwide apart, keep knees slightly bent. Squat down until thighs are parallel to floor. Keep back straight, bend and move hips backward to keep knees above feet. Return, keep knees slightly flexed. Repeat. Keep bodyweight on heels and look ahead or slightly above to keep back straight."}], "summary": "Grasp dumbbell with both hands at the sides of the upper plates. Hold dumbbell in front of chest, close to torso. Place feet about shoulderwide apart, keep knees slightly bent. Squat down until thighs are parallel to floor. Keep back straight, bend and move hips backward to keep knees above feet. Return, keep knees slightly flexed. Repeat. Keep bodyweight on heels and look ahead or slightly above to keep back straight.", "setup": "Grasp dumbbell with both hands at the sides of the upper plates.", "eccentric": "Hold dumbbell in front of chest, close to torso.", "concentric": "Place feet about shoulderwide apart, keep knees slightly bent. · Squat down until thighs are parallel to floor. · Keep back straight, bend and move hips backward to keep knees above feet. · Return, keep knees slightly flexed.", "regression": "Repeat.", "safety": "Keep bodyweight on heels and look ahead or slightly above to keep back straight."}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'quads',
    array[]::text[],
    4,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '9d29b08a-0cc1-5c81-9cce-0acec94a35f3'::uuid,
    'dumbbell_hammer_curl',
    'dumbbell hammer curl',
    '{"merged_steps": ["[''Stand up straight with a dumbbell in each hand, palms facing your torso.'', ''Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.'', ''This will be your starting position.'', ''Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Then, inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the recommended amount of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Stand up straight with a dumbbell in each hand, palms facing your torso.'', ''Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.'', ''This will be your starting position.'', ''Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Then, inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the recommended amount of repetitions.'']"], "description": "The dumbbell hammer curl is a strength exercise targeting the biceps and forearms. It is performed by curling dumbbells with a neutral grip (palms facing each other), which emphasizes the brachialis and brachioradialis muscles."}], "summary": "The dumbbell hammer curl is a strength exercise targeting the biceps and forearms. It is performed by curling dumbbells with a neutral grip (palms facing each other), which emphasizes the brachialis and brachioradialis muscles.", "setup": "[''Stand up straight with a dumbbell in each hand, palms facing your torso.'', ''Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.'', ''This will be your starting position.'', ''Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Then, inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the recommended amount of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'biceps',
    array['forearms'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/313.0.gif',
    'gif'
  ),
  (
    '565fe012-99fa-5389-8c01-308f2635df82'::uuid,
    'dumbbell_hammer_curl_v_2',
    'dumbbell hammer curl v. 2',
    '{"merged_steps": ["[''Stand up straight with a dumbbell in each hand, palms facing your torso.'', ''Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.'', ''This will be your starting position.'', ''Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Then, inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the recommended amount of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Stand up straight with a dumbbell in each hand, palms facing your torso.'', ''Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.'', ''This will be your starting position.'', ''Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Then, inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the recommended amount of repetitions.'']"], "description": "The dumbbell hammer curl v. 2 is a biceps-focused exercise performed with dumbbells, emphasizing the brachialis and forearm muscles. It is performed standing, with palms facing the torso, and involves curling the weights while keeping the upper arms stationary."}], "summary": "The dumbbell hammer curl v. 2 is a biceps-focused exercise performed with dumbbells, emphasizing the brachialis and forearm muscles. It is performed standing, with palms facing the torso, and involves curling the weights while keeping the upper arms stationary.", "setup": "[''Stand up straight with a dumbbell in each hand, palms facing your torso.'', ''Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward.'', ''This will be your starting position.'', ''Now, keeping the upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the weights until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Then, inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the recommended amount of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'biceps',
    array['forearms'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/312.0.gif',
    'gif'
  ),
  (
    'a6ba2bf0-d26d-58b6-903f-5adedcb193c2'::uuid,
    'dumbbell_hang_power_cleans',
    'Dumbbell Hang Power Cleans',
    '{"merged_steps": ["On your feet, stand tall with your dumbbells, holding them at your sides.", "Hinge at the hips to lower them to your knees (picture 1).", "Stand back up with a slight jump, using the momentum to pull the dumbbells up on to your shoulders (picture 2).", "Stand up straight, then lower under control to your sides and repeat.", "Keep this fast and explosive; if your heart rate doesn’t hit the roof, you’re doing them wrong."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["On your feet, stand tall with your dumbbells, holding them at your sides.", "Hinge at the hips to lower them to your knees (picture 1).", "Stand back up with a slight jump, using the momentum to pull the dumbbells up on to your shoulders (picture 2).", "Stand up straight, then lower under control to your sides and repeat.", "Keep this fast and explosive; if your heart rate doesn’t hit the roof, you’re doing them wrong."], "description": "On your feet, stand tall with your dumbbells, holding them at your sides. Hinge at the hips to lower them to your knees (picture 1). Stand back up with a slight jump, using the momentum to pull the dumbbells up on to your shoulders (picture 2). Stand up straight, then lower under control to your sides and repeat. Keep this fast and explosive; if your heart rate doesn’t hit the roof, you’re doing them wrong."}], "summary": "On your feet, stand tall with your dumbbells, holding them at your sides. Hinge at the hips to lower them to your knees (picture 1). Stand back up with a slight jump, using the momentum to pull the dumbbells up on to your shoulders (picture 2). Stand up straight, then lower under control to your sides and repeat. Keep this fast and explosive; if your heart rate doesn’t hit the roof, you’re doing them wrong.", "setup": "On your feet, stand tall with your dumbbells, holding them at your sides.", "eccentric": "Hinge at the hips to lower them to your knees (picture 1).", "concentric": "Stand back up with a slight jump, using the momentum to pull the dumbbells up on to your shoulders (picture 2).", "regression": "Stand up straight, then lower under control to your sides and repeat.", "safety": "Keep this fast and explosive; if your heart rate doesn’t hit the roof, you’re doing them wrong."}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'general',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    'ff1a4f23-2f40-5869-bd1e-07d684172bee'::uuid,
    'dumbbell_hex_press',
    'Dumbbell Hex Press',
    '{"merged_steps": ["* Muskulatur anspannen * Füße Breitpositionieren * Kontrollierte Bewegung * Langsame Bewegung * Gewichte zur unteren Brust/ Bauch führen"], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["* Muskulatur anspannen * Füße Breitpositionieren * Kontrollierte Bewegung * Langsame Bewegung * Gewichte zur unteren Brust/ Bauch führen"], "description": "* Muskulatur anspannen * Füße Breitpositionieren * Kontrollierte Bewegung * Langsame Bewegung * Gewichte zur unteren Brust/ Bauch führen"}], "summary": "* Muskulatur anspannen * Füße Breitpositionieren * Kontrollierte Bewegung * Langsame Bewegung * Gewichte zur unteren Brust/ Bauch führen", "setup": "* Muskulatur anspannen * Füße Breitpositionieren * Kontrollierte Bewegung * Langsame Bewegung * Gewichte zur unteren Brust/ Bauch führen"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'general',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    'cb2ef660-bb70-58da-ae07-a42afe5a9116'::uuid,
    'dumbbell_hip_thrust',
    'Dumbbell Hip Thrust',
    '{"merged_steps": ["Dumbbell hip thrust Begin seated on the ground with a bench placed horizontally behind you and your knees bent.", "Lay a dumbbell across your hips, holding either end with both hands.", "You may wish to place a pad or towel on your hips to increase comfort.", "With knees bent and feet firmly planted on the floor, lean back onto the bench so that it is gently pressing into your upper back.", "This is your starting position.", "Inhale.", "Exhale.", "Holding onto the dumbbell, press your heels into the mat and raise your hips off the floor until your body forms one straight line from chin to knee, resting your shoulders on the bench and ensuring that your head is an extension of your spine.", "Lower your hips to return to the starting position but without resting your glutes on the mat.", "Repeat for the specified number of repetitions."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Dumbbell hip thrust Begin seated on the ground with a bench placed horizontally behind you and your knees bent.", "Lay a dumbbell across your hips, holding either end with both hands.", "You may wish to place a pad or towel on your hips to increase comfort.", "With knees bent and feet firmly planted on the floor, lean back onto the bench so that it is gently pressing into your upper back.", "This is your starting position.", "Inhale.", "Exhale.", "Holding onto the dumbbell, press your heels into the mat and raise your hips off the floor until your body forms one straight line from chin to knee, resting your shoulders on the bench and ensuring that your head is an extension of your spine.", "Inhale.", "Lower your hips to return to the starting position but without resting your glutes on the mat.", "Repeat for the specified number of repetitions."], "description": "Dumbbell hip thrust Begin seated on the ground with a bench placed horizontally behind you and your knees bent. Lay a dumbbell across your hips, holding either end with both hands. You may wish to place a pad or towel on your hips to increase comfort. With knees bent and feet firmly planted on the floor, lean back onto the bench so that it is gently pressing into your upper back. This is your starting position. Inhale. Exhale. Holding onto the dumbbell, press your heels into the mat and raise your hips off the floor until your body forms one straight line from chin to knee, resting your shoulders on the bench and ensuring that your head is an extension of your spine. Inhale. Lower your hips to return to the starting position but without resting your glutes on the mat. Repeat for the specified number of repetitions."}], "summary": "Dumbbell hip thrust Begin seated on the ground with a bench placed horizontally behind you and your knees bent. Lay a dumbbell across your hips, holding either end with both hands. You may wish to place a pad or towel on your hips to increase comfort. With knees bent and feet firmly planted on the floor, lean back onto the bench so that it is gently pressing into your upper back. This is your starting position. Inhale. Exhale. Holding onto the dumbbell, press your heels into the mat and raise your hips off the floor until your body forms one straight line from chin to knee, resting your shoulders on the bench and ensuring that your head is an extension of your spine. Inhale. Lower your hips to return to the starting position but without resting your glutes on the mat. Repeat for the specified number of repetitions.", "setup": "Dumbbell hip thrust Begin seated on the ground with a bench placed horizontally behind you and your knees bent.", "eccentric": "Lay a dumbbell across your hips, holding either end with both hands.", "concentric": "You may wish to place a pad or towel on your hips to increase comfort. · With knees bent and feet firmly planted on the floor, lean back onto the bench so that it is gently pressing into your upper back. · This is your starting position. · Inhale. · Exhale. · Holding onto the dumbbell, press your heels into the mat and raise your hips off the floor until your body forms one straight line from chin to knee, resting your shoulders on the bench and ensuring that your head is an extension of your spine.", "regression": "Lower your hips to return to the starting position but without resting your glutes on the mat.", "safety": "Repeat for the specified number of repetitions."}'::jsonb,
    array['bench', 'dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'glutes',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    'f1a5ba7f-d5ac-55f9-8217-db324d9f8c1d'::uuid,
    'dumbbell_incline_bench_press',
    'dumbbell incline bench press',
    '{"merged_steps": ["[''Set up an incline bench at a 45-degree angle.'', ''Sit on the bench with your feet flat on the ground and your back pressed firmly against the bench.'', ''Hold a dumbbell in each hand, palms facing forward, and lift them to shoulder height.'', ''Slowly lower the dumbbells to the sides of your chest, keeping your elbows at a 90-degree angle.'', ''Push the dumbbells back up to the starting position, fully extending your arms.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Set up an incline bench at a 45-degree angle.'', ''Sit on the bench with your feet flat on the ground and your back pressed firmly against the bench.'', ''Hold a dumbbell in each hand, palms facing forward, and lift them to shoulder height.'', ''Slowly lower the dumbbells to the sides of your chest, keeping your elbows at a 90-degree angle.'', ''Push the dumbbells back up to the starting position, fully extending your arms.'', ''Repeat for the desired number of repetitions.'']"], "description": "The dumbbell incline bench press is a compound upper body exercise that targets the upper portion of the pectoral muscles, with additional emphasis on the shoulders and triceps. It is performed on an incline bench using dumbbells, requiring stability and control throughout the movement."}], "summary": "The dumbbell incline bench press is a compound upper body exercise that targets the upper portion of the pectoral muscles, with additional emphasis on the shoulders and triceps. It is performed on an incline bench using dumbbells, requiring stability and control throughout the movement.", "setup": "[''Set up an incline bench at a 45-degree angle.'', ''Sit on the bench with your feet flat on the ground and your back pressed firmly against the bench.'', ''Hold a dumbbell in each hand, palms facing forward, and lift them to shoulder height.'', ''Slowly lower the dumbbells to the sides of your chest, keeping your elbows at a 90-degree angle.'', ''Push the dumbbells back up to the starting position, fully extending your arms.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'push',
    'chest',
    array['delts', 'triceps'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/314.0.gif',
    'gif'
  ),
  (
    'b391029f-9f22-5eeb-9a44-fb49635012a2'::uuid,
    'dumbbell_incline_biceps_curl',
    'dumbbell incline biceps curl',
    '{"merged_steps": ["[''Sit on an incline bench with a dumbbell in each hand, palms facing forward, and arms fully extended.'', ''Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Sit on an incline bench with a dumbbell in each hand, palms facing forward, and arms fully extended.'', ''Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The dumbbell incline biceps curl is a strength exercise targeting the biceps, performed on an incline bench to increase the stretch and activation of the biceps muscle. It also engages the forearms as secondary muscles."}], "summary": "The dumbbell incline biceps curl is a strength exercise targeting the biceps, performed on an incline bench to increase the stretch and activation of the biceps muscle. It also engages the forearms as secondary muscles.", "setup": "[''Sit on an incline bench with a dumbbell in each hand, palms facing forward, and arms fully extended.'', ''Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'biceps',
    array['forearms'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/315.0.gif',
    'gif'
  ),
  (
    '9f22bce9-97cf-5819-8308-0ab617058028'::uuid,
    'dumbbell_incline_breeding',
    'dumbbell incline breeding',
    '{"merged_steps": ["[''Set up an incline bench at a 45-degree angle.'', ''Sit on the bench with your back against the pad and feet flat on the ground.'', ''Hold a dumbbell in each hand with an overhand grip, palms facing forward.'', ''Start with your arms fully extended, perpendicular to the ground.'', ''Lower the dumbbells slowly to the sides of your chest, keeping your elbows at a 90-degree angle.'', ''Pause for a moment at the bottom, then push the dumbbells back up to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Set up an incline bench at a 45-degree angle.'', ''Sit on the bench with your back against the pad and feet flat on the ground.'', ''Hold a dumbbell in each hand with an overhand grip, palms facing forward.'', ''Start with your arms fully extended, perpendicular to the ground.'', ''Lower the dumbbells slowly to the sides of your chest, keeping your elbows at a 90-degree angle.'', ''Pause for a moment at the bottom, then push the dumbbells back up to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The dumbbell incline breeding (likely a typo for ''dumbbell incline bench press'' or ''dumbbell incline fly'') is a chest exercise performed on an incline bench using dumbbells. It targets the upper chest (pectorals) and also works the shoulders and triceps."}], "summary": "The dumbbell incline breeding (likely a typo for ''dumbbell incline bench press'' or ''dumbbell incline fly'') is a chest exercise performed on an incline bench using dumbbells. It targets the upper chest (pectorals) and also works the shoulders and triceps.", "setup": "[''Set up an incline bench at a 45-degree angle.'', ''Sit on the bench with your back against the pad and feet flat on the ground.'', ''Hold a dumbbell in each hand with an overhand grip, palms facing forward.'', ''Start with your arms fully extended, perpendicular to the ground.'', ''Lower the dumbbells slowly to the sides of your chest, keeping your elbows at a 90-degree angle.'', ''Pause for a moment at the bottom, then push the dumbbells back up to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'push',
    'chest',
    array['delts', 'triceps'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/316.0.gif',
    'gif'
  ),
  (
    'd14cd1a5-21f0-5b43-8427-407447bdaa0b'::uuid,
    'dumbbell_incline_curl',
    'Dumbbell Incline Curl',
    '{"merged_steps": ["- **Setup:** Set an adjustable bench to an incline of approximately **45 to 60 degrees**.", "- **Starting Position:** Sit back against the bench with a dumbbell in each hand.", "Let your arms hang straight down toward the floor with your palms facing forward (supinated grip).", "- **The Curl:** Keeping your upper arms stationary and shoulders pinned back against the bench, exhale and curl the weights upward toward your shoulders.", "- **Peak Contraction:** Squeeze your biceps hard at the top of the movement, ensuring your elbows do not swing forward.", "- **The Descent:** Inhale and slowly lower the dumbbells back to the starting position, maintaining full control and feeling the stretch in the biceps.", "[''Set an incline bench to a 45-degree angle and sit on it with a dumbbell in each hand, palms facing forward.'', ''Rest your upper arms on the incline bench and let your elbows hang down, fully extending your arms.'', ''Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["- **Setup:** Set an adjustable bench to an incline of approximately **45 to 60 degrees**.", "- **Starting Position:** Sit back against the bench with a dumbbell in each hand.", "Let your arms hang straight down toward the floor with your palms facing forward (supinated grip).", "- **The Curl:** Keeping your upper arms stationary and shoulders pinned back against the bench, exhale and curl the weights upward toward your shoulders.", "- **Peak Contraction:** Squeeze your biceps hard at the top of the movement, ensuring your elbows do not swing forward.", "- **The Descent:** Inhale and slowly lower the dumbbells back to the starting position, maintaining full control and feeling the stretch in the biceps."], "description": "- **Setup:** Set an adjustable bench to an incline of approximately **45 to 60 degrees**. - **Starting Position:** Sit back against the bench with a dumbbell in each hand. Let your arms hang straight down toward the floor with your palms facing forward (supinated grip). - **The Curl:** Keeping your upper arms stationary and shoulders pinned back against the bench, exhale and curl the weights upward toward your shoulders. - **Peak Contraction:** Squeeze your biceps hard at the top of the movement, ensuring your elbows do not swing forward. - **The Descent:** Inhale and slowly lower the dumbbells back to the starting position, maintaining full control and feeling the stretch in the biceps."}, {"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Set an incline bench to a 45-degree angle and sit on it with a dumbbell in each hand, palms facing forward.'', ''Rest your upper arms on the incline bench and let your elbows hang down, fully extending your arms.'', ''Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The dumbbell incline curl is an isolation exercise targeting the biceps. Performed on an incline bench, it emphasizes the stretch and contraction of the biceps by reducing the involvement of the shoulders. This exercise is effective for building biceps strength and size."}], "summary": "- **Setup:** Set an adjustable bench to an incline of approximately **45 to 60 degrees**. - **Starting Position:** Sit back against the bench with a dumbbell in each hand. Let your arms hang straight down toward the floor with your palms facing forward (supinated grip). - **The Curl:** Keeping your upper arms stationary and shoulders pinned back against the bench, exhale and curl the weights upward toward your shoulders. - **Peak Contraction:** Squeeze your biceps hard at the top of the movement, ensuring your elbows do not swing forward. - **The Descent:** Inhale and slowly lower the dumbbells back to the starting position, maintaining full control and feeling the stretch in the biceps.", "setup": "- **Setup:** Set an adjustable bench to an incline of approximately **45 to 60 degrees**.", "eccentric": "- **Starting Position:** Sit back against the bench with a dumbbell in each hand.", "concentric": "Let your arms hang straight down toward the floor with your palms facing forward (supinated grip). · - **The Curl:** Keeping your upper arms stationary and shoulders pinned back against the bench, exhale and curl the weights upward toward your shoulders. · - **Peak Contraction:** Squeeze your biceps hard at the top of the movement, ensuring your elbows do not swing forward.", "regression": "- **The Descent:** Inhale and slowly lower the dumbbells back to the starting position, maintaining full control and feeling the stretch in the biceps.", "safety": "[''Set an incline bench to a 45-degree angle and sit on it with a dumbbell in each hand, palms facing forward.'', ''Rest your upper arms on the incline bench and let your elbows hang down, fully extending your arms.'', ''Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'biceps',
    array['brachialis', 'forearms'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/318.0.gif',
    'gif'
  ),
  (
    '80c217e0-59c7-54da-9cec-04f7c331dba9'::uuid,
    'dumbbell_incline_curl_v_2',
    'dumbbell incline curl v. 2',
    '{"merged_steps": ["[''Sit on an incline bench with a dumbbell in each hand, palms facing forward and arms fully extended.'', ''Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Sit on an incline bench with a dumbbell in each hand, palms facing forward and arms fully extended.'', ''Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The dumbbell incline curl v. 2 is a biceps-focused exercise performed on an incline bench. It isolates the biceps and forearms, requiring controlled movement to maximize muscle engagement."}], "summary": "The dumbbell incline curl v. 2 is a biceps-focused exercise performed on an incline bench. It isolates the biceps and forearms, requiring controlled movement to maximize muscle engagement.", "setup": "[''Sit on an incline bench with a dumbbell in each hand, palms facing forward and arms fully extended.'', ''Keeping your upper arms stationary, exhale and curl the weights while contracting your biceps.'', ''Continue to raise the dumbbells until your biceps are fully contracted and the dumbbells are at shoulder level.'', ''Hold the contracted position for a brief pause as you squeeze your biceps.'', ''Inhale and slowly begin to lower the dumbbells back to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['dumbbells', 'full_gym'],
    4,
    8,
    'isolation',
    'biceps',
    array['forearms'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/317.0.gif',
    'gif'
  ),
  (
    '487bf51a-4ffc-5a3d-ac9e-0c2620d99035'::uuid,
    'dumbbell_incline_fly',
    'Dumbbell Incline Fly',
    '{"merged_steps": ["This exercise involves lying on an incline bench and holding dumbbells in each hand.", "The arms are then extended out to the sides, parallel to the ground, and then brought back together in a hugging motion.", "This exercise primarily targets the chest muscles.", "[''Set an incline bench to a 45-degree angle.'', ''Sit on the bench with a dumbbell in each hand, palms facing each other.'', ''Lie back on the bench and press the dumbbells up to the starting position, directly above your chest.'', ''Lower the dumbbells out to the sides in a wide arc until you feel a stretch in your chest.'', ''Pause for a moment, then squeeze your chest muscles to bring the dumbbells back up to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["This exercise involves lying on an incline bench and holding dumbbells in each hand.", "The arms are then extended out to the sides, parallel to the ground, and then brought back together in a hugging motion.", "This exercise primarily targets the chest muscles."], "description": "This exercise involves lying on an incline bench and holding dumbbells in each hand. The arms are then extended out to the sides, parallel to the ground, and then brought back together in a hugging motion. This exercise primarily targets the chest muscles."}, {"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Set an incline bench to a 45-degree angle.'', ''Sit on the bench with a dumbbell in each hand, palms facing each other.'', ''Lie back on the bench and press the dumbbells up to the starting position, directly above your chest.'', ''Lower the dumbbells out to the sides in a wide arc until you feel a stretch in your chest.'', ''Pause for a moment, then squeeze your chest muscles to bring the dumbbells back up to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The dumbbell incline fly is a chest exercise performed on an incline bench, targeting the upper pectoral muscles. It involves lowering dumbbells out to the sides in a wide arc and then bringing them back together, emphasizing a stretch and contraction of the chest."}], "summary": "This exercise involves lying on an incline bench and holding dumbbells in each hand. The arms are then extended out to the sides, parallel to the ground, and then brought back together in a hugging motion. This exercise primarily targets the chest muscles.", "setup": "This exercise involves lying on an incline bench and holding dumbbells in each hand.", "eccentric": "The arms are then extended out to the sides, parallel to the ground, and then brought back together in a hugging motion.", "concentric": "This exercise primarily targets the chest muscles.", "safety": "[''Set an incline bench to a 45-degree angle.'', ''Sit on the bench with a dumbbell in each hand, palms facing each other.'', ''Lie back on the bench and press the dumbbells up to the starting position, directly above your chest.'', ''Lower the dumbbells out to the sides in a wide arc until you feel a stretch in your chest.'', ''Pause for a moment, then squeeze your chest muscles to bring the dumbbells back up to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['dumbbells', 'incline_bench', 'full_gym'],
    4,
    8,
    'push',
    'chest',
    array['delts'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/319.0.gif',
    'gif'
  )
on conflict (slug) do update set
  name = excluded.name,
  biomechanical_instructions = excluded.biomechanical_instructions,
  equipment_required = excluded.equipment_required,
  default_sets = excluded.default_sets,
  default_reps = excluded.default_reps,
  movement_pattern = excluded.movement_pattern,
  primary_muscle = excluded.primary_muscle,
  synergist_muscles = excluded.synergist_muscles,
  cns_fatigue_cost = excluded.cns_fatigue_cost,
  visual_asset_url = excluded.visual_asset_url,
  visual_asset_type = excluded.visual_asset_type;
