insert into public.library_exercises (
  id,
  slug,
  name,
  biomechanical_instructions,
  equipment_required,
  default_sets,
  default_reps,
  movement_pattern,
  primary_muscle,
  synergist_muscles,
  cns_fatigue_cost,
  joint_stress_profile,
  stretch_mediated_hypertrophy,
  visual_asset_url,
  visual_asset_type
) values
  (
    'b91906e1-ce06-5a36-b5c4-f67f31e91189'::uuid,
    'machine_lateral_wise',
    'Machine lateral wise',
    '{"merged_steps": ["The machine lateral raise is an isolation exercise that targets the medial (side) deltoid muscle to build wider, more defined shoulders.", "The machine''s fixed path of motion provides greater stability than dumbbells, making it ideal for beginners or those who want to focus solely on muscle activation."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["The machine lateral raise is an isolation exercise that targets the medial (side) deltoid muscle to build wider, more defined shoulders.", "The machine''s fixed path of motion provides greater stability than dumbbells, making it ideal for beginners or those who want to focus solely on muscle activation."], "description": "The machine lateral raise is an isolation exercise that targets the medial (side) deltoid muscle to build wider, more defined shoulders. The machine''s fixed path of motion provides greater stability than dumbbells, making it ideal for beginners or those who want to focus solely on muscle activation."}], "summary": "The machine lateral raise is an isolation exercise that targets the medial (side) deltoid muscle to build wider, more defined shoulders. The machine''s fixed path of motion provides greater stability than dumbbells, making it ideal for beginners or those who want to focus solely on muscle activation.", "setup": "The machine lateral raise is an isolation exercise that targets the medial (side) deltoid muscle to build wider, more defined shoulders.", "concentric": "The machine''s fixed path of motion provides greater stability than dumbbells, making it ideal for beginners or those who want to focus solely on muscle activation."}'::jsonb,
    array['gym_mat'],
    4,
    8,
    'isolation',
    'delts',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '5e3a5f60-6bf0-522a-8fb8-220e28ec3408'::uuid,
    'machine_side_lateral_raises',
    'Machine Side Lateral Raises',
    '{"merged_steps": ["Machine side lateral raises are an isolation exercise for the side (lateral) deltoids, performed on a machine for stability, targeting the outer shoulder by lifting pads or handles out to the sides to shoulder height, then lowering slowly, keeping elbows slightly bent and traps down to focus on the delts.", "This exercise helps build shoulder width by preventing swinging and providing constant tension, making it great for beginners or as a finisher.", "How to Perform Machine Lateral Raises Setup: Adjust the seat so your shoulders align with the machine''s pivot point, your chest is against the pad (or back if facing out), and your arms are at a 90-degree angle with the pads/handles.", "Starting Position: Grip the handles with a relaxed grip, elbows slightly bent, and shoulders down (depressed) away from your ears.", "Lifting Phase: Exhale and lift your arms out to the sides, moving your upper arms laterally, until they are parallel to the floor.", "Peak Contraction: Pause briefly at the top, squeezing the side delts, but don''t shrug your shoulders up.", "Lowering Phase: Inhale and slowly lower the weight back down with control, resisting the weight on the way down."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Machine side lateral raises are an isolation exercise for the side (lateral) deltoids, performed on a machine for stability, targeting the outer shoulder by lifting pads or handles out to the sides to shoulder height, then lowering slowly, keeping elbows slightly bent and traps down to focus on the delts.", "This exercise helps build shoulder width by preventing swinging and providing constant tension, making it great for beginners or as a finisher.", "How to Perform Machine Lateral Raises Setup: Adjust the seat so your shoulders align with the machine''s pivot point, your chest is against the pad (or back if facing out), and your arms are at a 90-degree angle with the pads/handles.", "Starting Position: Grip the handles with a relaxed grip, elbows slightly bent, and shoulders down (depressed) away from your ears.", "Lifting Phase: Exhale and lift your arms out to the sides, moving your upper arms laterally, until they are parallel to the floor.", "Peak Contraction: Pause briefly at the top, squeezing the side delts, but don''t shrug your shoulders up.", "Lowering Phase: Inhale and slowly lower the weight back down with control, resisting the weight on the way down."], "description": "Machine side lateral raises are an isolation exercise for the side (lateral) deltoids, performed on a machine for stability, targeting the outer shoulder by lifting pads or handles out to the sides to shoulder height, then lowering slowly, keeping elbows slightly bent and traps down to focus on the delts. This exercise helps build shoulder width by preventing swinging and providing constant tension, making it great for beginners or as a finisher. How to Perform Machine Lateral Raises Setup: Adjust the seat so your shoulders align with the machine''s pivot point, your chest is against the pad (or back if facing out), and your arms are at a 90-degree angle with the pads/handles. Starting Position: Grip the handles with a relaxed grip, elbows slightly bent, and shoulders down (depressed) away from your ears. Lifting Phase: Exhale and lift your arms out to the sides, moving your upper arms laterally, until they are parallel to the floor. Peak Contraction: Pause briefly at the top, squeezing the side delts, but don''t shrug your shoulders up. Lowering Phase: Inhale and slowly lower the weight back down with control, resisting the weight on the way down."}], "summary": "Machine side lateral raises are an isolation exercise for the side (lateral) deltoids, performed on a machine for stability, targeting the outer shoulder by lifting pads or handles out to the sides to shoulder height, then lowering slowly, keeping elbows slightly bent and traps down to focus on the delts. This exercise helps build shoulder width by preventing swinging and providing constant tension, making it great for beginners or as a finisher. How to Perform Machine Lateral Raises Setup: Adjust the seat so your shoulders align with the machine''s pivot point, your chest is against the pad (or back if facing out), and your arms are at a 90-degree angle with the pads/handles. Starting Position: Grip the handles with a relaxed grip, elbows slightly bent, and shoulders down (depressed) away from your ears. Lifting Phase: Exhale and lift your arms out to the sides, moving your upper arms laterally, until they are parallel to the floor. Peak Contraction: Pause briefly at the top, squeezing the side delts, but don''t shrug your shoulders up. Lowering Phase: Inhale and slowly lower the weight back down with control, resisting the weight on the way down.", "setup": "Machine side lateral raises are an isolation exercise for the side (lateral) deltoids, performed on a machine for stability, targeting the outer shoulder by lifting pads or handles out to the sides to shoulder height, then lowering slowly, keeping elbows slightly bent and traps down to focus on the delts.", "eccentric": "This exercise helps build shoulder width by preventing swinging and providing constant tension, making it great for beginners or as a finisher.", "concentric": "How to Perform Machine Lateral Raises Setup: Adjust the seat so your shoulders align with the machine''s pivot point, your chest is against the pad (or back if facing out), and your arms are at a 90-degree angle with the pads/handles. · Starting Position: Grip the handles with a relaxed grip, elbows slightly bent, and shoulders down (depressed) away from your ears. · Lifting Phase: Exhale and lift your arms out to the sides, moving your upper arms laterally, until they are parallel to the floor.", "regression": "Peak Contraction: Pause briefly at the top, squeezing the side delts, but don''t shrug your shoulders up.", "safety": "Lowering Phase: Inhale and slowly lower the weight back down with control, resisting the weight on the way down."}'::jsonb,
    array[]::text[],
    4,
    8,
    'isolation',
    'delts',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '0b526388-ddd4-5e0d-8e48-5db9b70eb301'::uuid,
    'march_or_jog_in_place',
    'March or jog in place',
    '{"merged_steps": ["Low-impact cardiovascular exercise that simulates running without moving, ideal for warming up, improving endurance, or training in small spaces."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Low-impact cardiovascular exercise that simulates running without moving, ideal for warming up, improving endurance, or training in small spaces."], "description": "Low-impact cardiovascular exercise that simulates running without moving, ideal for warming up, improving endurance, or training in small spaces."}], "summary": "Low-impact cardiovascular exercise that simulates running without moving, ideal for warming up, improving endurance, or training in small spaces.", "setup": "Low-impact cardiovascular exercise that simulates running without moving, ideal for warming up, improving endurance, or training in small spaces."}'::jsonb,
    array['none_bodyweight_exercise'],
    4,
    8,
    'isolation',
    'hamstrings',
    array['delts', 'biceps', 'obliquus_externus_abdominis', 'core', 'triceps'],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    'a2cc5fda-5cdb-508b-8c9c-05eae64d27ea'::uuid,
    'march_sit_wall',
    'march sit (wall)',
    '{"merged_steps": ["[''Stand with your back against a wall and your feet hip-width apart.'', ''Slowly slide your back down the wall until your knees are bent at a 90-degree angle.'', ''Lift your right foot off the ground and bring your knee towards your chest.'', ''Lower your right foot back down and lift your left foot off the ground, bringing your knee towards your chest.'', ''Continue alternating between lifting your right and left foot for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Stand with your back against a wall and your feet hip-width apart.'', ''Slowly slide your back down the wall until your knees are bent at a 90-degree angle.'', ''Lift your right foot off the ground and bring your knee towards your chest.'', ''Lower your right foot back down and lift your left foot off the ground, bringing your knee towards your chest.'', ''Continue alternating between lifting your right and left foot for the desired number of repetitions.'']"], "description": "The march sit (wall) is a lower body exercise performed with body weight, targeting the glutes and also engaging the quadriceps, hamstrings, and calves. It involves holding a wall sit position while alternately lifting each knee towards the chest, mimicking a marching motion."}], "summary": "The march sit (wall) is a lower body exercise performed with body weight, targeting the glutes and also engaging the quadriceps, hamstrings, and calves. It involves holding a wall sit position while alternately lifting each knee towards the chest, mimicking a marching motion.", "setup": "[''Stand with your back against a wall and your feet hip-width apart.'', ''Slowly slide your back down the wall until your knees are bent at a 90-degree angle.'', ''Lift your right foot off the ground and bring your knee towards your chest.'', ''Lower your right foot back down and lift your left foot off the ground, bringing your knee towards your chest.'', ''Continue alternating between lifting your right and left foot for the desired number of repetitions.'']"}'::jsonb,
    array['bodyweight'],
    4,
    8,
    'squat',
    'glutes',
    array['quadriceps', 'hamstrings', 'calves'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/624.0.gif',
    'gif'
  ),
  (
    '06138347-4149-5ed6-a20f-15a7686ad4ab'::uuid,
    'meadows_row',
    'Meadows Row',
    '{"merged_steps": ["The Meadows row is a unilateral row performed with a landmine setup, overhand grip, and staggered stance.", "Lean your torso forward and grip the barbell.", "Rest the other forearm on the forward leg.", "Start this movement by driving the elbow behind you while retracting the shoulder-blade.", "Keep the working shoulder down.", "Pull toward your back hip until the elbow is level with your torso."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["The Meadows row is a unilateral row performed with a landmine setup, overhand grip, and staggered stance.", "Lean your torso forward and grip the barbell.", "Rest the other forearm on the forward leg.", "Start this movement by driving the elbow behind you while retracting the shoulder-blade.", "Keep the working shoulder down.", "Pull toward your back hip until the elbow is level with your torso."], "description": "The Meadows row is a unilateral row performed with a landmine setup, overhand grip, and staggered stance. Lean your torso forward and grip the barbell. Rest the other forearm on the forward leg. Start this movement by driving the elbow behind you while retracting the shoulder-blade. Keep the working shoulder down. Pull toward your back hip until the elbow is level with your torso."}], "summary": "The Meadows row is a unilateral row performed with a landmine setup, overhand grip, and staggered stance. Lean your torso forward and grip the barbell. Rest the other forearm on the forward leg. Start this movement by driving the elbow behind you while retracting the shoulder-blade. Keep the working shoulder down. Pull toward your back hip until the elbow is level with your torso.", "setup": "The Meadows row is a unilateral row performed with a landmine setup, overhand grip, and staggered stance.", "eccentric": "Lean your torso forward and grip the barbell.", "concentric": "Rest the other forearm on the forward leg. · Start this movement by driving the elbow behind you while retracting the shoulder-blade.", "regression": "Keep the working shoulder down.", "safety": "Pull toward your back hip until the elbow is level with your torso."}'::jsonb,
    array['barbell', 'full_gym'],
    4,
    8,
    'isolation',
    'lats',
    array['biceps', 'core'],
    5,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    'be49aba5-eded-5258-bd9e-9d5e239cde27'::uuid,
    'medicine_ball_booklet_crunch',
    'Medicine ball booklet crunch',
    '{"merged_steps": ["Using a medicine ball as an overload will make the exercise heavier."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Using a medicine ball as an overload will make the exercise heavier."], "description": "Using a medicine ball as an overload will make the exercise heavier."}], "summary": "Using a medicine ball as an overload will make the exercise heavier.", "setup": "Using a medicine ball as an overload will make the exercise heavier."}'::jsonb,
    array['none_bodyweight_exercise'],
    4,
    8,
    'isolation',
    'core',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '903860fd-00c8-5206-8003-469fbee09740'::uuid,
    'medicine_ball_twist',
    'Medicine ball twist',
    '{"merged_steps": ["In a seated position, the torso is rotated from side to side without forcing, approaching the knees and making the ball touch the ground from time to time"], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["In a seated position, the torso is rotated from side to side without forcing, approaching the knees and making the ball touch the ground from time to time"], "description": "In a seated position, the torso is rotated from side to side without forcing, approaching the knees and making the ball touch the ground from time to time"}], "summary": "In a seated position, the torso is rotated from side to side without forcing, approaching the knees and making the ball touch the ground from time to time", "setup": "In a seated position, the torso is rotated from side to side without forcing, approaching the knees and making the ball touch the ground from time to time"}'::jsonb,
    array['swiss_ball'],
    4,
    8,
    'isolation',
    'obliquus_externus_abdominis',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    'aeca5665-e96c-5a1c-8c92-1a4ae1137b60'::uuid,
    'meditaci_n_guiada_o_libre',
    'Meditación guiada o libre',
    '{"merged_steps": ["Ejercicio mental de atención plena (mindfulness) que ayuda a reducir ansiedad, mejorar el enfoque y el bienestar general."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Ejercicio mental de atención plena (mindfulness) que ayuda a reducir ansiedad, mejorar el enfoque y el bienestar general."], "description": "Ejercicio mental de atención plena (mindfulness) que ayuda a reducir ansiedad, mejorar el enfoque y el bienestar general."}], "summary": "Ejercicio mental de atención plena (mindfulness) que ayuda a reducir ansiedad, mejorar el enfoque y el bienestar general.", "setup": "Ejercicio mental de atención plena (mindfulness) que ayuda a reducir ansiedad, mejorar el enfoque y el bienestar general."}'::jsonb,
    array['none_bodyweight_exercise'],
    4,
    8,
    'isolation',
    'general',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    'de00e36b-8d70-537a-89f9-2999958a9218'::uuid,
    'military_press_mit_sz_bar',
    'Military Press mit SZ-Bar',
    '{"merged_steps": ["On an SZ-bar grip your hands on the outside of each bend and stand with your arms straight down, palms facing your legs.", "Pull the bar (bending your arms at the elbow) to your chest, and the push the bar above your head (arms as straight as possible).", "Return the bar to your chest by dropping your arms at the elbows.", "Return the bar to it''s origional position (stand with your arms straight down, palms facing your legs.)"], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["On an SZ-bar grip your hands on the outside of each bend and stand with your arms straight down, palms facing your legs.", "Pull the bar (bending your arms at the elbow) to your chest, and the push the bar above your head (arms as straight as possible).", "Return the bar to your chest by dropping your arms at the elbows.", "Return the bar to it''s origional position (stand with your arms straight down, palms facing your legs.)"], "description": "On an SZ-bar grip your hands on the outside of each bend and stand with your arms straight down, palms facing your legs. Pull the bar (bending your arms at the elbow) to your chest, and the push the bar above your head (arms as straight as possible). Return the bar to your chest by dropping your arms at the elbows. Return the bar to it''s origional position (stand with your arms straight down, palms facing your legs.)"}], "summary": "On an SZ-bar grip your hands on the outside of each bend and stand with your arms straight down, palms facing your legs. Pull the bar (bending your arms at the elbow) to your chest, and the push the bar above your head (arms as straight as possible). Return the bar to your chest by dropping your arms at the elbows. Return the bar to it''s origional position (stand with your arms straight down, palms facing your legs.)", "setup": "On an SZ-bar grip your hands on the outside of each bend and stand with your arms straight down, palms facing your legs.", "eccentric": "Pull the bar (bending your arms at the elbow) to your chest, and the push the bar above your head (arms as straight as possible).", "concentric": "Return the bar to your chest by dropping your arms at the elbows.", "safety": "Return the bar to it''s origional position (stand with your arms straight down, palms facing your legs.)"}'::jsonb,
    array['sz_bar'],
    4,
    8,
    'isolation',
    'general',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '5bb1c199-a85f-5dcb-98d9-f2f0919539d5'::uuid,
    'mixed_grip_chin_up',
    'mixed grip chin-up',
    '{"merged_steps": ["[''Grab the pull-up bar with an underhand grip (palms facing towards you) and your hands slightly wider than shoulder-width apart.'', ''Hang from the bar with your arms fully extended and your feet off the ground.'', ''Engage your back muscles and pull your body up towards the bar, leading with your chest.'', ''Continue pulling until your chin is above the bar.'', ''Pause for a moment at the top, then slowly lower your body back down to the starting position with control.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Grab the pull-up bar with an underhand grip (palms facing towards you) and your hands slightly wider than shoulder-width apart.'', ''Hang from the bar with your arms fully extended and your feet off the ground.'', ''Engage your back muscles and pull your body up towards the bar, leading with your chest.'', ''Continue pulling until your chin is above the bar.'', ''Pause for a moment at the top, then slowly lower your body back down to the starting position with control.'', ''Repeat for the desired number of repetitions.'']"], "description": "The mixed grip chin-up is a bodyweight exercise targeting the lats, with secondary emphasis on the biceps and forearms. It involves pulling your body up to a bar using a mixed grip, which challenges grip strength and upper body pulling power."}], "summary": "The mixed grip chin-up is a bodyweight exercise targeting the lats, with secondary emphasis on the biceps and forearms. It involves pulling your body up to a bar using a mixed grip, which challenges grip strength and upper body pulling power.", "setup": "[''Grab the pull-up bar with an underhand grip (palms facing towards you) and your hands slightly wider than shoulder-width apart.'', ''Hang from the bar with your arms fully extended and your feet off the ground.'', ''Engage your back muscles and pull your body up towards the bar, leading with your chest.'', ''Continue pulling until your chin is above the bar.'', ''Pause for a moment at the top, then slowly lower your body back down to the starting position with control.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['bodyweight'],
    4,
    8,
    'pull',
    'lats',
    array['biceps', 'forearms'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/627.0.gif',
    'gif'
  ),
  (
    'd6fa020c-4a30-576c-9694-9d8abb495182'::uuid,
    'modified_pulldown',
    'Modified pulldown',
    '{"merged_steps": ["With an inclined bench in front of the pulldown machine, use a close-grip to do latfocused pulldowns."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["With an inclined bench in front of the pulldown machine, use a close-grip to do latfocused pulldowns."], "description": "With an inclined bench in front of the pulldown machine, use a close-grip to do latfocused pulldowns."}], "summary": "With an inclined bench in front of the pulldown machine, use a close-grip to do latfocused pulldowns.", "setup": "With an inclined bench in front of the pulldown machine, use a close-grip to do latfocused pulldowns."}'::jsonb,
    array['incline_bench'],
    4,
    8,
    'isolation',
    'lats',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '1e54279f-9757-5770-a2f1-408c5a41e119'::uuid,
    'monster_walk',
    'monster walk',
    '{"merged_steps": ["[''Place a resistance band around your ankles.'', ''Stand with your feet shoulder-width apart and slightly bend your knees.'', ''Take a step to the side with your right foot, maintaining tension on the resistance band.'', ''Follow with your left foot, stepping to the side to return to the starting position.'', ''Repeat for the desired number of repetitions, then switch sides.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Place a resistance band around your ankles.'', ''Stand with your feet shoulder-width apart and slightly bend your knees.'', ''Take a step to the side with your right foot, maintaining tension on the resistance band.'', ''Follow with your left foot, stepping to the side to return to the starting position.'', ''Repeat for the desired number of repetitions, then switch sides.'']"], "description": "The monster walk is a lower body exercise that targets the glutes and also works the hamstrings and quadriceps. It is typically performed with a resistance band around the ankles to increase intensity. The movement involves stepping side-to-side while maintaining tension in the band and a slight knee bend."}], "summary": "The monster walk is a lower body exercise that targets the glutes and also works the hamstrings and quadriceps. It is typically performed with a resistance band around the ankles to increase intensity. The movement involves stepping side-to-side while maintaining tension in the band and a slight knee bend.", "setup": "[''Place a resistance band around your ankles.'', ''Stand with your feet shoulder-width apart and slightly bend your knees.'', ''Take a step to the side with your right foot, maintaining tension on the resistance band.'', ''Follow with your left foot, stepping to the side to return to the starting position.'', ''Repeat for the desired number of repetitions, then switch sides.'']"}'::jsonb,
    array['body_weight_with_resistance_band'],
    4,
    8,
    'squat',
    'glutes',
    array['hamstrings', 'quadriceps'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/628.0.gif',
    'gif'
  ),
  (
    '52e12433-e6f3-5e4a-ac61-df2c260d92ec'::uuid,
    'mountain_climber',
    'mountain climber',
    '{"merged_steps": ["[''Start in a high plank position with your hands directly under your shoulders and your body in a straight line.'', ''Engage your core and bring your right knee towards your chest, then quickly switch and bring your left knee towards your chest.'', ''Continue alternating legs in a running motion, keeping your hips low and your core engaged.'', ''Maintain a steady pace and breathe evenly throughout the exercise.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Start in a high plank position with your hands directly under your shoulders and your body in a straight line.'', ''Engage your core and bring your right knee towards your chest, then quickly switch and bring your left knee towards your chest.'', ''Continue alternating legs in a running motion, keeping your hips low and your core engaged.'', ''Maintain a steady pace and breathe evenly throughout the exercise.'', ''Repeat for the desired number of repetitions.'']"], "description": "Mountain climbers are a dynamic bodyweight exercise that targets the cardiovascular system while also engaging the core, shoulders, and triceps. The movement mimics a running motion in a plank position, making it effective for both cardio and muscular endurance."}], "summary": "Mountain climbers are a dynamic bodyweight exercise that targets the cardiovascular system while also engaging the core, shoulders, and triceps. The movement mimics a running motion in a plank position, making it effective for both cardio and muscular endurance.", "setup": "[''Start in a high plank position with your hands directly under your shoulders and your body in a straight line.'', ''Engage your core and bring your right knee towards your chest, then quickly switch and bring your left knee towards your chest.'', ''Continue alternating legs in a running motion, keeping your hips low and your core engaged.'', ''Maintain a steady pace and breathe evenly throughout the exercise.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['bodyweight'],
    4,
    8,
    'isolation',
    'cardiovascular_system',
    array['core', 'delts', 'triceps'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/630.0.gif',
    'gif'
  ),
  (
    'dbf22612-7cd8-50fd-9b8b-4fdc44742734'::uuid,
    'mountain_climbers',
    'Mountain climbers',
    '{"merged_steps": ["Starting position: Start in the upright push-up position, aka.", "the high plank position.Hands should be directly under your shoulders.Keep your head in line with your back, facing the floor.Feet should be about hip-width apart.", "Steps: 1.", "Move one knee toward the center of your body, towards your elbows, keeping the other leg extended.", "2.", "In a quick jumping movement, straighten the bent leg out and pull the other knee toward your body.", "3.", "Keep repeating step 2, alternating legs.", "Notes: Throughout the exercise, your back should remain as straight as possible – avoid a hump or a sagging back."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Starting position: Start in the upright push-up position, aka.", "the high plank position.Hands should be directly under your shoulders.Keep your head in line with your back, facing the floor.Feet should be about hip-width apart.", "Steps: 1.", "Move one knee toward the center of your body, towards your elbows, keeping the other leg extended.", "2.", "In a quick jumping movement, straighten the bent leg out and pull the other knee toward your body.", "3.", "Keep repeating step 2, alternating legs.", "Notes: Throughout the exercise, your back should remain as straight as possible – avoid a hump or a sagging back."], "description": "Starting position: Start in the upright push-up position, aka. the high plank position.Hands should be directly under your shoulders.Keep your head in line with your back, facing the floor.Feet should be about hip-width apart. Steps: 1. Move one knee toward the center of your body, towards your elbows, keeping the other leg extended. 2. In a quick jumping movement, straighten the bent leg out and pull the other knee toward your body. 3. Keep repeating step 2, alternating legs. Notes: Throughout the exercise, your back should remain as straight as possible – avoid a hump or a sagging back."}], "summary": "Starting position: Start in the upright push-up position, aka. the high plank position.Hands should be directly under your shoulders.Keep your head in line with your back, facing the floor.Feet should be about hip-width apart. Steps: 1. Move one knee toward the center of your body, towards your elbows, keeping the other leg extended. 2. In a quick jumping movement, straighten the bent leg out and pull the other knee toward your body. 3. Keep repeating step 2, alternating legs. Notes: Throughout the exercise, your back should remain as straight as possible – avoid a hump or a sagging back.", "setup": "Starting position: Start in the upright push-up position, aka.", "eccentric": "the high plank position.Hands should be directly under your shoulders.Keep your head in line with your back, facing the floor.Feet should be about hip-width apart.", "concentric": "Steps: 1. · Move one knee toward the center of your body, towards your elbows, keeping the other leg extended. · 2. · In a quick jumping movement, straighten the bent leg out and pull the other knee toward your body. · 3.", "regression": "Keep repeating step 2, alternating legs.", "safety": "Notes: Throughout the exercise, your back should remain as straight as possible – avoid a hump or a sagging back."}'::jsonb,
    array['none_bodyweight_exercise'],
    4,
    8,
    'isolation',
    'general',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '5ec30f40-8a6b-5635-83c3-f2f0900f5d6f'::uuid,
    'muscle_up',
    'Muscle up',
    '{"merged_steps": ["The body is then explosively pulled up by the arms in a radial pull-up, with greater speed than a regular pull-up.", "When the bar approaches the upper chest, the wrists are swiftly flexed to bring the forearms above the bar.", "The body is leaned forward, and the elbows are straightened by activating the triceps.", "The routine is considered complete when the bar is at the level of the waist and the arms are fully straight.", "To dismount, the arms are bent at the elbow, and the body is lowered to the floor, and the exercise can be repeated.", "As a relatively advanced exercise, muscle-ups are typically first learned with an assistive kip.", "The legs swing (kip) up and provide momentum to assist in the explosive upward force needed to ascend above the bar.", "More advanced athletes can perform a strict variation of the muscle-up which is done slowly, without any kip.", "This variation begins with a still dead hang and uses isometric muscle contraction to ascend above the bar in a slow, controlled fashion.", "[''Start by hanging from a pull-up bar with your palms facing away from you and your arms fully extended.'', ''Engage your core and pull your body up towards the bar, leading with your chest.'', ''As you reach the top of the movement, transition your grip so that your palms are facing towards you.'', ''Continue pulling yourself up until your chest is above the bar and your arms are fully flexed.'', ''Reverse the movement by slowly lowering yourself back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["The body is then explosively pulled up by the arms in a radial pull-up, with greater speed than a regular pull-up.", "When the bar approaches the upper chest, the wrists are swiftly flexed to bring the forearms above the bar.", "The body is leaned forward, and the elbows are straightened by activating the triceps.", "The routine is considered complete when the bar is at the level of the waist and the arms are fully straight.", "To dismount, the arms are bent at the elbow, and the body is lowered to the floor, and the exercise can be repeated.", "As a relatively advanced exercise, muscle-ups are typically first learned with an assistive kip.", "The legs swing (kip) up and provide momentum to assist in the explosive upward force needed to ascend above the bar.", "More advanced athletes can perform a strict variation of the muscle-up which is done slowly, without any kip.", "This variation begins with a still dead hang and uses isometric muscle contraction to ascend above the bar in a slow, controlled fashion."], "description": "The body is then explosively pulled up by the arms in a radial pull-up, with greater speed than a regular pull-up. When the bar approaches the upper chest, the wrists are swiftly flexed to bring the forearms above the bar. The body is leaned forward, and the elbows are straightened by activating the triceps. The routine is considered complete when the bar is at the level of the waist and the arms are fully straight. To dismount, the arms are bent at the elbow, and the body is lowered to the floor, and the exercise can be repeated. As a relatively advanced exercise, muscle-ups are typically first learned with an assistive kip. The legs swing (kip) up and provide momentum to assist in the explosive upward force needed to ascend above the bar. More advanced athletes can perform a strict variation of the muscle-up which is done slowly, without any kip. This variation begins with a still dead hang and uses isometric muscle contraction to ascend above the bar in a slow, controlled fashion."}, {"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Start by hanging from a pull-up bar with your palms facing away from you and your arms fully extended.'', ''Engage your core and pull your body up towards the bar, leading with your chest.'', ''As you reach the top of the movement, transition your grip so that your palms are facing towards you.'', ''Continue pulling yourself up until your chest is above the bar and your arms are fully flexed.'', ''Reverse the movement by slowly lowering yourself back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The muscle up is a challenging bodyweight exercise that combines a pull-up with a dip, requiring significant upper body strength, coordination, and explosive power. It targets the lats primarily, with secondary engagement of the biceps, triceps, shoulders, and chest."}], "summary": "The body is then explosively pulled up by the arms in a radial pull-up, with greater speed than a regular pull-up. When the bar approaches the upper chest, the wrists are swiftly flexed to bring the forearms above the bar. The body is leaned forward, and the elbows are straightened by activating the triceps. The routine is considered complete when the bar is at the level of the waist and the arms are fully straight. To dismount, the arms are bent at the elbow, and the body is lowered to the floor, and the exercise can be repeated. As a relatively advanced exercise, muscle-ups are typically first learned with an assistive kip. The legs swing (kip) up and provide momentum to assist in the explosive upward force needed to ascend above the bar. More advanced athletes can perform a strict variation of the muscle-up which is done slowly, without any kip. This variation begins with a still dead hang and uses isometric muscle contraction to ascend above the bar in a slow, controlled fashion.", "setup": "The body is then explosively pulled up by the arms in a radial pull-up, with greater speed than a regular pull-up.", "eccentric": "When the bar approaches the upper chest, the wrists are swiftly flexed to bring the forearms above the bar.", "concentric": "The body is leaned forward, and the elbows are straightened by activating the triceps. · The routine is considered complete when the bar is at the level of the waist and the arms are fully straight. · To dismount, the arms are bent at the elbow, and the body is lowered to the floor, and the exercise can be repeated. · As a relatively advanced exercise, muscle-ups are typically first learned with an assistive kip. · The legs swing (kip) up and provide momentum to assist in the explosive upward force needed to ascend above the bar. · More advanced athletes can perform a strict variation of the muscle-up which is done slowly, without any kip.", "regression": "This variation begins with a still dead hang and uses isometric muscle contraction to ascend above the bar in a slow, controlled fashion.", "safety": "[''Start by hanging from a pull-up bar with your palms facing away from you and your arms fully extended.'', ''Engage your core and pull your body up towards the bar, leading with your chest.'', ''As you reach the top of the movement, transition your grip so that your palms are facing towards you.'', ''Continue pulling yourself up until your chest is above the bar and your arms are fully flexed.'', ''Reverse the movement by slowly lowering yourself back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['bodyweight', 'pull_up_bar'],
    4,
    8,
    'pull',
    'biceps',
    array['biceps', 'triceps', 'delts', 'chest'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/631.0.gif',
    'gif'
  ),
  (
    '1f189ca9-8851-5203-b56e-29b59addafae'::uuid,
    'nan',
    'nan',
    '{"merged_steps": ["nan"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["nan"], "description": "nan"}], "summary": "nan", "setup": "nan"}'::jsonb,
    array[]::text[],
    4,
    8,
    'isolation',
    'general',
    array[]::text[],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/0nan.gif',
    'gif'
  ),
  (
    '4fdf299c-c106-598b-9c07-c851b19bd892'::uuid,
    'neck_bridge_prone',
    'neck bridge prone',
    '{"merged_steps": ["[''Place a thick pad on the floor; kneel with toes tucked, hands under shoulders, and forehead on the pad.'', ''Gently tuck the chin to create a long neck and brace your abs.'', ''Press into your forehead and toes to lift the knees slightly, raising the hips into a pike.'', ''With hands lightly assisting, slowly shift your body forward to load the forehead without collapsing the neck.'', ''Pause briefly, then shift back to reduce load while maintaining alignment and steady breathing.'', ''Perform small, pain-free rocks for reps, keeping movements slow and controlled.'', ''Lower the knees back to the floor to exit the position.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Place a thick pad on the floor; kneel with toes tucked, hands under shoulders, and forehead on the pad.'', ''Gently tuck the chin to create a long neck and brace your abs.'', ''Press into your forehead and toes to lift the knees slightly, raising the hips into a pike.'', ''With hands lightly assisting, slowly shift your body forward to load the forehead without collapsing the neck.'', ''Pause briefly, then shift back to reduce load while maintaining alignment and steady breathing.'', ''Perform small, pain-free rocks for reps, keeping movements slow and controlled.'', ''Lower the knees back to the floor to exit the position.'']"], "description": "Kneel on a padded surface and place your forehead on the mat with hands for support, hips high. Shift your weight between forehead and toes in small, controlled rocks to strengthen the neck while keeping a tucked-chin position."}], "summary": "Kneel on a padded surface and place your forehead on the mat with hands for support, hips high. Shift your weight between forehead and toes in small, controlled rocks to strengthen the neck while keeping a tucked-chin position.", "setup": "[''Place a thick pad on the floor; kneel with toes tucked, hands under shoulders, and forehead on the pad.'', ''Gently tuck the chin to create a long neck and brace your abs.'', ''Press into your forehead and toes to lift the knees slightly, raising the hips into a pike.'', ''With hands lightly assisting, slowly shift your body forward to load the forehead without collapsing the neck.'', ''Pause briefly, then shift back to reduce load while maintaining alignment and steady breathing.'', ''Perform small, pain-free rocks for reps, keeping movements slow and controlled.'', ''Lower the knees back to the floor to exit the position.'']"}'::jsonb,
    array['bodyweight'],
    4,
    8,
    'isolation',
    'levator_scapulae',
    array['traps', 'upper_back', 'core'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/633.0.gif',
    'gif'
  ),
  (
    '9660ec5b-e3bd-5f4c-aa9b-b28741b28356'::uuid,
    'neck_extension',
    'Neck extension',
    '{"merged_steps": ["Unilateral triceps exercise with your back to the pulley, with the pulley at the top"], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Unilateral triceps exercise with your back to the pulley, with the pulley at the top"], "description": "Unilateral triceps exercise with your back to the pulley, with the pulley at the top"}], "summary": "Unilateral triceps exercise with your back to the pulley, with the pulley at the top", "setup": "Unilateral triceps exercise with your back to the pulley, with the pulley at the top"}'::jsonb,
    array['sz_bar'],
    4,
    8,
    'isolation',
    'biceps',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    'cceee580-d193-57d8-a237-1652a1418bc5'::uuid,
    'neck_half_circles',
    'Neck half circles',
    '{"merged_steps": ["Starting position: Start sitting or standing.", "Lean your head against one of your shoulders, but don''t push.", "Steps: In one slower fluid motion and with your head relaxed and not pushing in any direction: 1.", "bring your head down toward your chest.", "2.", "then lean back aganst your other shoulder.", "3.", "then back toward the chest again.4.and finally toward the starting position.", "Keep repeating this."], "sources": [{"source": "wger", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\wger-master\\wger\\exercises\\fixtures\\exercise-base-data.json", "steps": ["Starting position: Start sitting or standing.", "Lean your head against one of your shoulders, but don''t push.", "Steps: In one slower fluid motion and with your head relaxed and not pushing in any direction: 1.", "bring your head down toward your chest.", "2.", "then lean back aganst your other shoulder.", "3.", "then back toward the chest again.4.and finally toward the starting position.", "Keep repeating this."], "description": "Starting position: Start sitting or standing. Lean your head against one of your shoulders, but don''t push. Steps: In one slower fluid motion and with your head relaxed and not pushing in any direction: 1. bring your head down toward your chest. 2. then lean back aganst your other shoulder. 3. then back toward the chest again.4.and finally toward the starting position. Keep repeating this."}], "summary": "Starting position: Start sitting or standing. Lean your head against one of your shoulders, but don''t push. Steps: In one slower fluid motion and with your head relaxed and not pushing in any direction: 1. bring your head down toward your chest. 2. then lean back aganst your other shoulder. 3. then back toward the chest again.4.and finally toward the starting position. Keep repeating this.", "setup": "Starting position: Start sitting or standing.", "eccentric": "Lean your head against one of your shoulders, but don''t push.", "concentric": "Steps: In one slower fluid motion and with your head relaxed and not pushing in any direction: 1. · bring your head down toward your chest. · 2. · then lean back aganst your other shoulder. · 3.", "regression": "then back toward the chest again.4.and finally toward the starting position.", "safety": "Keep repeating this."}'::jsonb,
    array['none_bodyweight_exercise'],
    4,
    8,
    'isolation',
    'general',
    array[]::text[],
    3,
    'low_impact',
    false,
    NULL,
    NULL
  ),
  (
    '9f85007d-cb34-593b-9146-e055fc7853cb'::uuid,
    'negative_crunch',
    'negative crunch',
    '{"merged_steps": ["[''Lie flat on your back with your knees bent and feet flat on the ground.'', ''Place your hands behind your head with your elbows pointing outwards.'', ''Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.'', ''Pause for a moment at the top, then slowly lower your upper body back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "sources": [{"source": "exercisedb-csv", "file": "C:\\Users\\kaiqu\\Desktop\\SOMMA\\datasets\\final_exercise_dataset.csv", "steps": ["[''Lie flat on your back with your knees bent and feet flat on the ground.'', ''Place your hands behind your head with your elbows pointing outwards.'', ''Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.'', ''Pause for a moment at the top, then slowly lower your upper body back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"], "description": "The negative crunch is an abdominal exercise focusing on the eccentric (lowering) phase of the crunch to increase core strength and control."}], "summary": "The negative crunch is an abdominal exercise focusing on the eccentric (lowering) phase of the crunch to increase core strength and control.", "setup": "[''Lie flat on your back with your knees bent and feet flat on the ground.'', ''Place your hands behind your head with your elbows pointing outwards.'', ''Engaging your abs, slowly lift your upper body off the ground, curling forward until your torso is at a 45-degree angle.'', ''Pause for a moment at the top, then slowly lower your upper body back down to the starting position.'', ''Repeat for the desired number of repetitions.'']"}'::jsonb,
    array['bodyweight'],
    4,
    8,
    'isolation',
    'core',
    array['hip_flexors'],
    3,
    'low_impact',
    false,
    'https://static.exercisedb.dev/media/gifs/634.0.gif',
    'gif'
  )
on conflict (slug) do update set
  name = excluded.name,
  biomechanical_instructions = excluded.biomechanical_instructions,
  equipment_required = excluded.equipment_required,
  default_sets = excluded.default_sets,
  default_reps = excluded.default_reps,
  movement_pattern = excluded.movement_pattern,
  primary_muscle = excluded.primary_muscle,
  synergist_muscles = excluded.synergist_muscles,
  cns_fatigue_cost = excluded.cns_fatigue_cost,
  visual_asset_url = excluded.visual_asset_url,
  visual_asset_type = excluded.visual_asset_type;
