-- SOMMA Global Encyclopedia Catalog Seed
-- Generated by scripts/import_catalog.py (massive ingestion)
-- Safe to re-run: ON CONFLICT (slug) DO UPDATE

alter table public.library_exercises drop constraint if exists library_exercises_visual_asset_type_check;
alter table public.library_combat drop constraint if exists library_combat_visual_asset_type_check;
alter table public.library_flow_spirit drop constraint if exists library_flow_spirit_visual_asset_type_check;

alter table public.library_exercises
  add constraint library_exercises_visual_asset_type_check
  check (visual_asset_type is null or visual_asset_type in ('lottie', 'svg', 'mp4', 'webm', 'gif', 'webp'));

alter table public.library_combat
  add constraint library_combat_visual_asset_type_check
  check (visual_asset_type is null or visual_asset_type in ('lottie', 'svg', 'mp4', 'webm', 'gif', 'webp'));

alter table public.library_flow_spirit
  add constraint library_flow_spirit_visual_asset_type_check
  check (visual_asset_type is null or visual_asset_type in ('lottie', 'svg', 'mp4', 'webm', 'gif', 'webp'));

-- library_combat batch 1/1 (21 rows)
insert into public.library_combat (
  id,
  slug,
  combo_name,
  sequence,
  complexity_level,
  tactical_focus,
  visual_asset_url,
  visual_asset_type
) values
  (
    '5eb961f7-4b69-5240-a2c6-d7e2b3750a63'::uuid,
    'cable_cross_over',
    'Cable Cross-over',
    '["Cable Cross-over"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    '3bd44cc0-2018-57ab-a788-e7c0e303f4cd'::uuid,
    'cable_cross_over_lateral_pulldown',
    'cable cross-over lateral pulldown',
    '["cable cross-over lateral pulldown"]'::jsonb,
    3,
    'footwork_range',
    'https://static.exercisedb.dev/media/gifs/153.0.gif',
    'gif'
  ),
  (
    'c9605b01-5a77-59a8-8433-18e368cdee43'::uuid,
    'cable_cross_over_reverse_fly',
    'cable cross-over reverse fly',
    '["cable cross-over reverse fly"]'::jsonb,
    3,
    'footwork_range',
    'https://static.exercisedb.dev/media/gifs/154.0.gif',
    'gif'
  ),
  (
    '1401a954-c7ab-5dca-8421-c1d7e1f1fe30'::uuid,
    'cable_cross_over_variation',
    'cable cross-over variation',
    '["cable cross-over variation"]'::jsonb,
    3,
    'footwork_range',
    'https://static.exercisedb.dev/media/gifs/155.0.gif',
    'gif'
  ),
  (
    'b1c14dd0-1b79-5eca-8cdf-5a55438efa92'::uuid,
    'cable_standing_cross_over_high_reverse_fly',
    'cable standing cross-over high reverse fly',
    '["cable standing cross-over high reverse fly"]'::jsonb,
    3,
    'footwork_range',
    'https://static.exercisedb.dev/media/gifs/225.0.gif',
    'gif'
  ),
  (
    '8ef2657e-20c0-5cf5-82a7-757aaf5ad45b'::uuid,
    'cross_body_crunch',
    'cross body crunch',
    '["cross body crunch"]'::jsonb,
    3,
    'footwork_range',
    'https://static.exercisedb.dev/media/gifs/262.0.gif',
    'gif'
  ),
  (
    'c665ba9b-6d21-5549-805f-11565d8d1259'::uuid,
    'cross_bench_dumbbell_pullovers',
    'Cross-Bench Dumbbell Pullovers',
    '["Cross-Bench Dumbbell Pullovers"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    'e5350dfe-6e80-5b97-a492-4e0efa8594d7'::uuid,
    'cross_body_cable_y_raise',
    'Cross-Body Cable Y-Raise',
    '["Cross-Body Cable Y-Raise"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    'f7aada7f-5f82-5440-8dcf-e2cbd528ab6e'::uuid,
    'crossbody_hamstring_stretch',
    'Crossbody Hamstring Stretch',
    '["Crossbody Hamstring Stretch"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    'ba07d967-387c-5417-8894-bc5b0a8c3093'::uuid,
    'crossbody_leg_swings',
    'Crossbody Leg Swings',
    '["Crossbody Leg Swings"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    '18e4c85b-3ce0-5180-943f-3cee1cf22d89'::uuid,
    'db_cross_body_hammer_curls',
    'DB Cross Body Hammer Curls',
    '["DB Cross Body Hammer Curls"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    '429b2470-30d3-50ca-a619-7316efab1497'::uuid,
    'dumbbell_cross_body_hammer_curl',
    'dumbbell cross body hammer curl',
    '["dumbbell cross body hammer curl"]'::jsonb,
    3,
    'footwork_range',
    'https://static.exercisedb.dev/media/gifs/298.0.gif',
    'gif'
  ),
  (
    '8b0d779b-143a-5c05-bed9-d5f1743af177'::uuid,
    'dumbbell_iron_cross',
    'dumbbell iron cross',
    '["dumbbell iron cross"]'::jsonb,
    3,
    'footwork_range',
    'https://static.exercisedb.dev/media/gifs/332.0.gif',
    'gif'
  ),
  (
    'a739ea57-1b26-57f8-8f3d-65a4453cda52'::uuid,
    'dumbbell_lying_extension_across_face',
    'dumbbell lying extension (across face)',
    '["dumbbell lying extension (across face)"]'::jsonb,
    3,
    'footwork_range',
    'https://static.exercisedb.dev/media/gifs/337.0.gif',
    'gif'
  ),
  (
    '45b6ab1a-d131-50dd-a8d2-250f38f5d2a0'::uuid,
    'high_cable_cross_tricep_extention_nb',
    'High-Cable Cross Tricep Extention - NB',
    '["High-Cable Cross Tricep Extention - NB"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    'ecfe99f9-bfa3-5c69-b6ae-613ec6ea719c'::uuid,
    'hip_crossover',
    'Hip Crossover',
    '["Hip Crossover"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    '6ded4429-b57c-51e0-86e4-4a7231d2b6b4'::uuid,
    'lat_pulldown_cross_body_single_arm',
    'Lat Pulldown - Cross Body Single Arm',
    '["Lat Pulldown - Cross Body Single Arm"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    'a468da67-fb5f-5b5e-9c04-19077ff96541'::uuid,
    'low_cable_cross_over_nb',
    'Low-Cable Cross-Over - NB',
    '["Low-Cable Cross-Over - NB"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    '82ebbae7-d1ea-5ae2-b2a0-8dfd825d1410'::uuid,
    'omni_cable_cross_over',
    'Omni Cable Cross-over',
    '["Omni Cable Cross-over"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    '5b571201-83b0-5a98-8c01-879386e93e7b'::uuid,
    'suspended_crossess',
    'Suspended crossess',
    '["Suspended crossess"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  ),
  (
    '651eed5c-9460-5773-92bc-5e4d67d64aca'::uuid,
    'unilateral_cross_body_cable_pull_down',
    'unilateral cross body cable pull down',
    '["unilateral cross body cable pull down"]'::jsonb,
    3,
    'footwork_range',
    NULL,
    NULL
  )
on conflict (slug) do update set
  combo_name = excluded.combo_name,
  sequence = excluded.sequence,
  complexity_level = excluded.complexity_level,
  tactical_focus = excluded.tactical_focus,
  visual_asset_url = excluded.visual_asset_url,
  visual_asset_type = excluded.visual_asset_type;
